# Default values for wellbore-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

data:
  requestsCpu: "0.1"
  requestsMemory: "1G"
  limitsCpu: "1"
  limitsMemory: "3G"
  image: "community.opengroup.org:5555/osdu/platform/domain-data-mgmt-services/wellbore/wellbore-domain-services/osdu-gcp-wellbore:latest"
  imagePullPolicy: "IfNotPresent"
  serviceAccountName: "wellbore"

conf:
  configmap: "wellbore-config"
  appName: "wellbore"
  keycloakSecretName: "wellbore-keycloak-secret"
  minioSecretName: "wellbore-minio-secret"
  domain: ""
  onPremEnabled: false
