# Default values for wellbore-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

data:
  requests_cpu: "0.1"
  requests_memory: "1024M"
  limits_cpu: "1"
  limits_memory: "2G"
  image: "community.opengroup.org:5555/osdu/platform/domain-data-mgmt-services/wellbore/wellbore-domain-services/osdu-gcp:latest"
  imagePullPolicy: "IfNotPresent"
  serviceAccountName: ""

conf:
  configmap: "wellbore-config"
  app_name: "wellbore"
  
