#  Copyright © Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - /**/*.md
      - .gitignore
      - /docs

resources:
  repositories:
  - repository: FluxRepo
    type: git
    name: k8-gitops-manifests
  - repository: TemplateRepo
    type: git
    name: infra-azure-provisioning

variables:
  - group: 'Azure - OSDU'
  - group: 'Azure - OSDU Secrets'
  - template: template/vars/global_vars.yml

stages:
  - template: template/build-stage.yml
    parameters:
      # TODO: The following templates needs to be injected as parameters
      postBuildTemplate: TO_BE_DEFINED
      postBuildTemplateParameters: {}

  - template: template/deploy-stages.yml
    parameters:
      providers:
        - name: Azure
          short_name: az
          varGroupPrefix: ""
          environments: 
          - name: dev
            # TODO: The following templates needs to be injected as parameters
            authenticationTemplate: TO_BE_DEFINED
            authenticationTemplateParameters: {}
          getImageTemplate: TO_BE_DEFINED
          getImageTemplateParameters: {}