variables:
  OSDU_GCP_SERVICE: wellbore
  OSDU_GCP_VENDOR: gcp
  OSDU_GCP_INT_TEST_TYPE: python

osdu-gcp-containerize-gitlab:
  variables:
    BUILD_PATH: "./build/Dockerfile"
    BUILD_ARGS: >
      --build-arg PIP_WHEEL_DIR=python-packages
      --build-arg build_date="$CI_JOB_STARTED_AT"
      --build-arg build_number=$CI_COMMIT_SHORT_SHA
      --build-arg commit_id=$CI_COMMIT_SHORT_SHA
      --build-arg build_origin="Gitlab"
      --build-arg commit_branch=$CI_COMMIT_BRANCH
  # check if it possible to be deleted before release 0.17 [GONRG-5590]
  before_script:
    - sed -i "s|osdu-api==0.14.0|osdu_api~=0.15.0|g" requirements.txt
    - sed -i "s|osdu-core-lib-python-anthos==1.0.0|osdu-core-lib-python-anthos==1.0.1|g" requirements.txt
    - sed -i "s|osdu-core-lib-python-aws==1.0.1|# osdu-core-lib-python-aws==1.0.1|g" requirements.txt

osdu-gcp-containerize-gcr:
  variables:
    BUILD_PATH: "./build/Dockerfile"
    BUILD_ARGS: >
      --build-arg PIP_WHEEL_DIR=python-packages
      --build-arg build_date="$CI_JOB_STARTED_AT"
      --build-arg build_number=$CI_COMMIT_SHORT_SHA
      --build-arg commit_id=$CI_COMMIT_SHORT_SHA
      --build-arg build_origin="Gitlab"
      --build-arg commit_branch=$CI_COMMIT_BRANCH
  # check if it possible to be deleted before release 0.17 [GONRG-5590]
  before_script:
    - cat $OSDU_GCP_DEPLOY_FILE | docker login -u _json_key --password-stdin https://gcr.io
    - sed -i "s|osdu-api==0.14.0|osdu_api~=0.15.0|g" requirements.txt
    - sed -i "s|osdu-core-lib-python-anthos==1.0.0|osdu-core-lib-python-anthos==1.0.1|g" requirements.txt
    - sed -i "s|osdu-core-lib-python-aws==1.0.1|# osdu-core-lib-python-aws==1.0.1|g" requirements.txt

osdu-gcp-test-python:
  extends: .osdu-gcp-variables
  stage: integration
  image: python:3.8
  needs: ["osdu-gcp-deploy-deployment"]
  script:
    - bash
    - curl https://sdk.cloud.google.com > install.sh
    - bash install.sh --disable-prompts
    - source /root/google-cloud-sdk/completion.bash.inc
    - source /root/google-cloud-sdk/path.bash.inc
    - python3 -m venv env
    - source env/bin/activate
    - pip install --upgrade pip
    - pip install wheel
    - >
      for REQ in $PIP_REQUIREMENTS ; do
        pip install -r $REQ
      done
    - cd tests/integration
    - echo $OSDU_GCP_INTEGRATION_TESTER | base64 -d > file.json
    - gcloud auth activate-service-account --key-file file.json
    - gcloud config set project $OSDU_GCP_PROJECT
    - >
      python gen_postman_env.py
      --token $(gcloud auth print-access-token)
      --base_url $OSDU_GCP_WELLBORE_BASE_URL
      --cloud_provider $OSDU_GCP_VENDOR
      --data_partition $OSDU_GCP_TENANT
      --acl_domain $DOMAIN
      --legal_tag $LEGAL_TAG
    - pytest ./functional --environment="./generated/postman_environment.json" --filter-tag=!search -p no:randomly

osdu-gcp-dev2-test-python:
  extends: .osdu-gcp-dev2-variables
  stage: integration
  image: python:3.8
  needs: ["osdu-gcp-dev2-deploy-deployment"]
  script:
    - bash
    - curl https://sdk.cloud.google.com > install.sh
    - bash install.sh --disable-prompts
    - source /root/google-cloud-sdk/completion.bash.inc
    - source /root/google-cloud-sdk/path.bash.inc
    - python3 -m venv env
    - source env/bin/activate
    - pip install --upgrade pip
    - pip install wheel pytest pytest-cov
    - >
      for REQ in $PIP_REQUIREMENTS ; do
        pip install -r $REQ
      done
    - cd tests/integration
    - echo $OSDU_GCP_INTEGRATION_TESTER | base64 -d > file.json
    - gcloud auth activate-service-account --key-file file.json
    - gcloud config set project $OSDU_GCP_PROJECT
    - >
      python gen_postman_env.py
      --token $(gcloud auth print-access-token)
      --base_url $OSDU_GCP_WELLBORE_BASE_URL
      --cloud_provider $OSDU_GCP_VENDOR
      --data_partition $OSDU_GCP_TENANT
      --acl_domain $DOMAIN
      --legal_tag $LEGAL_TAG
    - pytest ./functional --environment="./generated/postman_environment.json" --filter-tag=!search

osdu-gcp-anthos-test-python:
  extends: .osdu-gcp-anthos-variables
  stage: integration
  image: python:3.8
  needs: ["osdu-gcp-anthos-deploy-deployment"]
  script:
    - bash
    - wget -O /usr/local/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
    - chmod +x /usr/local/bin/jq
    - >
      export TOKEN=$(curl --location --request POST "$TEST_OPENID_PROVIDER_URL/protocol/openid-connect/token"
      --header "Content-Type: application/x-www-form-urlencoded"
      --data-urlencode "client_id=$TEST_OPENID_PROVIDER_CLIENT_ID"
      --data-urlencode "client_secret=$TEST_OPENID_PROVIDER_CLIENT_SECRET"
      --data-urlencode "scope=openid"
      --data-urlencode "grant_type=client_credentials" | jq -r ".id_token")
    - python3 -m venv env
    - source env/bin/activate
    - pip install --upgrade pip
    - pip install wheel
    - >
      for REQ in $PIP_REQUIREMENTS ; do
        pip install -r $REQ
      done
    - cd tests/integration
    - >
      python gen_postman_env.py
      --token $TOKEN
      --base_url $OSDU_GCP_WELLBORE_BASE_URL
      --cloud_provider "anthos"
      --data_partition $OSDU_GCP_TENANT
      --acl_domain $DOMAIN
      --legal_tag $LEGAL_TAG
    - pytest ./functional --environment="./generated/postman_environment.json" --filter-tag='!search|!chunking' -p no:randomly

# Disable maven job in gcp common gke pipelines
osdu-gcp-test:
  extends:
    - .osdu-gcp-variables

osdu-gcp-dev2-test:
  extends:
    - .osdu-gcp-dev2-variables

osdu-gcp-anthos-test:
  extends:
    - .osdu-gcp-anthos-variables
