# Copyright 2021 Schlumberger
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen:
#   filename:  openapi_curated.yaml
#   timestamp: 2020-03-25T08:19:10+00:00

# - Warning :
#   This file is no longer generated
#   If you want to generate new version please make sure to not break the changes made to the file

from __future__ import annotations

from datetime import date, datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import ConfigDict, RootModel, BaseModel, Field, StrictFloat, StrictStr, StrictInt
from typing_extensions import Annotated

# TMP: added import only to expose pydantic bug with non-deterministic coercion
# https://github.com/samuelcolvin/pydantic/issues/2835
# import requests


class Tags(RootModel):
    #model_config = ConfigDict(extra="allow")

    root: str


# forbid unknown field in the root of the models
class DDMSBaseModel(BaseModel):
    """
    The base model forbids fields which are not declared initially in the pydantic model
    """
    model_config = ConfigDict(extra="forbid")


# only allow unknown field in the data
class DDMSBaseModelWithExtra(BaseModel):
    """
    Used for data model allows extra fields which are not declared initially in the pydantic model
    """
    model_config = ConfigDict(extra="allow")


class LinkList(DDMSBaseModelWithExtra):
    pass


class Kind(str, Enum):
    CRS = 'CRS'
    Unit = 'Unit'
    Measurement = 'Measurement'
    AzimuthReference = 'AzimuthReference'
    DateTime = 'DateTime'


class MetaItem(DDMSBaseModelWithExtra):
    kind: Kind = Field(
        ...,
        description='The kind of reference, unit, measurement, CRS or azimuth reference.',
        title='Reference Kind',
    )
    name: Optional[str] = Field(
        None,
        description='The name of the CRS or the symbol/name of the unit',
        title='Name or Symbol',
    )
    persistableReference: str = Field(
        ...,
        description='The persistable reference string uniquely identifying the CRS or Unit',
        title='Persistable Reference',
    )
    propertyNames: Optional[List[str]] = Field(
        None,
        description='The list of property names, to which this meta data item provides Unit/CRS context to. Data structures, which come in a single frame of reference, can register the property name, others require a full path like "data.structureA.propertyB" to define a unique context.',
        title='Attribute Names',
    )
    propertyValues: Optional[List[str]] = Field(
        None,
        description='The list of property values, to which this meta data item provides Unit/CRS context to. Typically a unit symbol is a value to a data structure; this symbol is then registered in this propertyValues array and the persistableReference provides the absolute reference.',
        title='Attribute Names',
    )
    uncertainty: Optional[float] = Field(
        None,
        description='The uncertainty of the values measured given the unit or CRS unit.',
        title='Uncertainty',
    )


# Common Elements for entities
class DDMSBaseRecord(BaseModel):
    ancestry: Optional[LinkList] = Field(
        None,
        description='The links to data, which constitute the inputs.',
        title='Ancestry',
    )
    meta: Optional[List[MetaItem]] = Field(
        None,
        description="The meta data section linking the 'unitKey', 'crsKey' to self-contained definitions (persistableReference)",
        title='Frame of Reference Meta Data',
    )
    type: Optional[str] = Field(
        None,
        description='The reference entity type as declared in common:metadata:entity:*.',
        title='Entity Type',
    )
    tags: Optional[Dict[str, Tags]] = Field(
        None,
        description='A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.',
        examples=[{'NameOfKey': 'String value'}],
        title='Tag Dictionary',
    )
    createTime: Optional[datetime] = Field(
        None,
        description='Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.',
        examples=['2020-12-16T11:46:20.163Z'],
        title='Resource Object Creation DateTime',
    )
    createUser: Optional[str] = Field(
        None,
        description='The user reference, which created the first version of this resource object. Set by the System.',
        examples=['some-user@some-company-cloud.com'],
        title='Resource Object Creation User Reference',
    )
    modifyTime: Optional[datetime] = Field(
        None,
        description='Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.',
        examples=['2020-12-16T11:52:24.477Z'],
        title='Resource Object Version Creation DateTime',
    )
    modifyUser: Optional[str] = Field(
        None,
        description='The user reference, which created this version of this resource object. Set by the System.',
        examples=['some-user@some-company-cloud.com'],
        title='Resource Object Version Creation User Reference',
    )


class Point(DDMSBaseModel):
    latitude: Optional[Annotated[float, Field(ge=-90.0, le=90.0)]] = Field(
        None, description='Latitude of point.'
    )
    longitude: Optional[Annotated[float, Field(ge=-180.0, le=180.0)]] = Field(
        None, description='Longitude of point.'
    )


class Legal(DDMSBaseModel):
    legaltags: Optional[List[str]] = Field(
        None,
        description='The list of legal tags, see compliance API.',
        title='Legal Tags',
    )
    otherRelevantDataCountries: Optional[List[str]] = Field(
        None,
        description='The list of other relevant data countries using the ISO 2-letter codes, see compliance API.',
        title='Other Relevant Data Countries',
    )
    status: Optional[str] = Field(
        None, description='The legal status.', title='Legal Status'
    )


class TagDictionary(DDMSBaseModelWithExtra):
    pass


class ToOneRelationship(DDMSBaseModel):
    confidence: Optional[float] = Field(
        None,
        description='The confidence of the relationship. If the property is absent a well-known relation is implied.',
        title='Relationship Confidence',
    )
    id: Optional[str] = Field(
        None,
        description='The id of the related object in the Data Ecosystem. If set, the id has priority over the natural key in the name property.',
        title='Related Object Id',
    )
    name: Optional[str] = Field(
        None,
        description='The name or natural key of the related object. This property is required if the target object id could not (yet) be identified.',
        title='Related Object Name',
    )
    version: Optional[float] = Field(
        None,
        description='The version number of the related entity. If no version number is specified, the last version is implied.',
        title='Entity Version Number',
    )


class ValueWithUnit(DDMSBaseModel):
    unitKey: str = Field(
        ...,
        description="Unit for value of the corresponding attribute for the domain object in question. The key can be looked up in the 'frameOfReference.units' for further details.",
        title='Unit Key',
    )
    value: float = Field(
        ...,
        description='Value of the corresponding attribute for the domain object in question.',
        title='Value',
    )


class DataType(Enum):
    string = 'string'
    number = 'number'
    integer = 'integer'
    boolean = 'boolean'


class Format(Enum):
    date = 'date'
    date_time = 'date-time'
    time = 'time'
    byte = 'byte'
    binary = 'binary'
    boolean = 'boolean'
    email = 'email'
    uuid = 'uuid'
    uri = 'uri'
    int8 = 'int8'
    int16 = 'int16'
    int32 = 'int32'
    int64 = 'int64'
    float32 = 'float32'
    float64 = 'float64'
    float128 = 'float128'


class dipsetrelationships(DDMSBaseModelWithExtra):
    well: Optional[ToOneRelationship] = Field(
        None,
        description='The well to which this dipSet belongs. Only required if the wellbore is unknown.',
        title='Well',
    )
    wellbore: ToOneRelationship = Field(
        ..., description='The wellbore to which this dipSet belongs.', title='Wellbore'
    )
    wellboreSection: Optional[ToOneRelationship] = Field(
        None,
        description='The wellbore section to which this dipSet belongs.',
        title='Wellbore Section',
    )
    referenceLog: Optional[ToOneRelationship] = Field(
        None,
        description='The true dip azimuth log of the dipset.',
        title='True dip azimuth log',
    )
    trueDipAzimuthLog: Optional[ToOneRelationship] = Field(
        None,
        description='The true dip azimuth log of the dipset.',
        title='True dip azimuth log',
    )
    trueDipInclinationLog: Optional[ToOneRelationship] = Field(
        None,
        description='The X-coordinate log of the dipset',
        title='X-coordinate log',
    )
    xCoordinateLog: Optional[ToOneRelationship] = Field(
        None,
        description='The X-coordinate log of the dipset',
        title='X-coordinate log',
    )
    yCoordinateLog: Optional[ToOneRelationship] = Field(
        None,
        description='The Y-coordinate log of the dipset',
        title='Y-coordinate log',
    )
    zCoordinateLog: Optional[ToOneRelationship] = Field(
        None,
        description='The Z-coordinate log of the dipset',
        title='Z-coordinate log',
    )
    qualityLog: Optional[ToOneRelationship] = Field(
        None,
        description='The quality log of the dipset',
        title='Quality log',
    )
    classificationLog: Optional[ToOneRelationship] = Field(
        None,
        description='The classification log of the dipset',
        title='Classification log',
    )


class DataType_2(Enum):
    string = 'string'
    number = 'number'
    integer = 'integer'
    boolean = 'boolean'
    date_time = 'date-time'


class Format_2(Enum):
    date = 'date'
    date_time = 'date-time'
    time = 'time'
    byte = 'byte'
    binary = 'binary'
    email = 'email'
    uuid = 'uuid'
    uri = 'uri'
    int8 = 'int8'
    int16 = 'int16'
    int32 = 'int32'
    int64 = 'int64'
    float32 = 'float32'
    float64 = 'float64'
    float128 = 'float128'


class historyRecord(DDMSBaseModel):
    date: Optional[datetime] = Field(
        None,
        description='The UTC date time of the log creation/processing',
        title='Date and Time',
    )
    description: Optional[str] = Field(
        None,
        description='The description of the context, which produced the log.',
        title=' Description',
    )
    user: Optional[str] = Field(
        None, description='The user running the log processing.', title='User'
    )


class ReferenceType(Enum):
    Date = 'Date'
    Date_Time = 'Date Time'
    Measured_Depth = 'Measured Depth'
    Core_depth = 'Core depth'
    True_Vertical_Depth = 'True Vertical Depth'
    True_Vertical_Depth_Sub_Sea = 'True Vertical Depth Sub Sea'
    One_Way_Time = 'One-Way Time'
    Two_Way_Time = 'Two-Way Time'


class logRelationships(DDMSBaseModelWithExtra):
    logSet: Optional[ToOneRelationship] = Field(
        None,
        description='The logSet to which this log belongs. If the log is not part of a log set this relationship stays empty.',
        title='LogSet',
    )
    timeDepthRelation: Optional[ToOneRelationship] = Field(
        None,
        description='The timeDepthRelation to which this log belongs. If the log is not part of a timeDepthRelation this relationship stays empty.',
        title='TimeDepthRelation LogSet',
    )
    well: Optional[ToOneRelationship] = Field(
        None,
        description='The well to which this log belongs. Only required if the wellbore is unknown.',
        title='Well',
    )
    wellbore: Optional[ToOneRelationship] = Field(
        None,
        description='The wellbore to which this log belongs. This relationship is the most important; only the wellbore can provide the unique context for the measured depth index.',
        title='Wellbore',
    )


class namedProperty(DDMSBaseModel):
    """
    namedProperty Model
    """
    associations: Optional[List[str]] = Field(
        None,
        description='The optional associations contains one or more mnemonics found elsewhere in the logSet.',
        title='Associations',
    )
    description: Optional[str] = Field(
        None,
        description='The description and role of this property.',
        title='Property Description',
    )
    format: Optional[str] = Field(
        None,
        description="An optional format declaration for the property values. The 'A' prefix indicates an array; string values are represented by 'S'; floating point values are represented by 'F', optionally followed by a field specification, e.g. 'F10.4'; exponential number representations are represented by 'E'; integer values are represented by 'I'. For further information see the LAS specification http://www.cwls.org/las/.",
        title='Format (LAS)',
    )
    name: Optional[str] = Field(
        None, description='The name of this property.', title='Property Name'
    )
    unitKey: Optional[str] = Field(
        None,
        description="The unitKey to be looked up in the 'frameOfReference.units' dictionary to find the self-contained definition.",
        title='Property Unit Symbol',
    )

    # original type definition for value:
    # pydantic coerces when possible, but to *what* is ambiguous here.
    # value: Optional[Union[float, str]] = Field(

    # if we want to rely on coercion, it needs to be unambiguous
    # value: Optional[float] = Field(  # but we would size-down the accepted type

    # otherwise we use StrictFloat and StrictStr to prevent unexpected (non-deterministic) coercion
    # we add StrictInt to keep accepting int, as int was implicitely coerced to float
    value: Optional[Union[StrictFloat, StrictInt, StrictStr]] = Field(
        None,
        description='The value for this property as a string or a number.',
        title='Property Value',
    )
    values: Optional[List[float]] = Field(
        None,
        description='The values, e.g. interval boundaries, for this property.',
        title='Property Values (Interval)',
    )


class channel(DDMSBaseModel):
    absentValue: Optional[str] = Field(
        None,
        description='Optional field carrying the absent value as string for this channel.',
        title='Absent Value',
    )
    dataType: Optional[DataType] = Field(
        'number',
        description="The log value type (per log sample). The 'format' property may contain further hints about data type presentation.",
        title='Data Type',
    )
    dimension: Optional[int] = Field(
        None, description='The dimension of this log or channel', title='Dimension'
    )
    family: Optional[str] = Field(
        None,
        description='The log family code of this log or channel (optional)',
        title='Log Family',
    )
    familyType: Optional[str] = Field(
        None,
        description="The log family type code of this log or channel. Example: 'Neutron Porosity' for 'Thermal Neutron Porosity Sandstone'. (optional)",
        title='Log Family Type',
    )
    format: Optional[Format] = Field(
        'float32',
        description="Optional format hint how to treat the log values as strings or number of bits per 'dataType'.",
        title='Format Hint',
    )
    logstoreId: Optional[float] = Field(
        None,
        description='The id of this log or channel in the Logstore. This property is not present in the index channel.',
        title='Logstore ID',
    )
    bulkURI: Optional[str] = Field(
        None,
        description='bulkURI either URL or URN.',
        title='bulk URI',
    )
    longName: Optional[str] = Field(
        None, description='The long name of this log or channel', title='Log Long Name'
    )
    mnemonic: Optional[str] = Field(
        None, description='The mnemonic of this log or channel', title='Mnemonic'
    )
    name: Optional[str] = Field(
        None, description='The name of this log or channel.', title='Log Name'
    )
    properties: Optional[List[namedProperty]] = Field(
        None,
        description='The named properties of this log or channel.',
        title='Named Properties',
    )
    source: Optional[str] = Field(
        None,
        description='The source of this log or channel as a data reference; Typically this refers to the raw LogSet, from which this log WKE is generated.',
        title='Source',
    )
    unitKey: Optional[str] = Field(
        None,
        description="The unitKey to be looked up in the 'frameOfReference.units' dictionary to find the self-contained definition.",
        title='Unit',
    )

class SimpleElevationReference(DDMSBaseModel):
    elevationFromMsl: ValueWithUnit = Field(
        ...,
        description="The elevation above mean sea level (MSL), at which the vertical origin is 0.0. The 'unitKey' is further defined in 'frameOfReference.units'.",
        title='Elevation from MSL',
    )
    name: Optional[str] = Field(
        None,
        description='The name of the Elevation Reference.',
        title='Elevation Reference Name',
    )


class logchannel(DDMSBaseModel):
    columnNames: Optional[List[str]] = Field(
        None,
        description="A list of names for multi-dimensional logs (dimension>1). The length of this array is expected to be equal to 'dimension'. For one-dimensional this property stays empty as the columnName is by definition the log name.",
        title='Column Names',
    )
    dataType: Optional[DataType_2] = Field(
        'number',
        description="The log value type (per log sample). The 'format' property may contain further hints about data type presentation.",
        title='Data Type',
    )
    dimension: Optional[int] = Field(
        None, description='The dimension of this log or channel', title='Dimension'
    )
    family: Optional[str] = Field(
        None,
        description='The log family code of this log or channel (optional)',
        title='Log Family',
    )
    familyType: Optional[str] = Field(
        None,
        description="The log family type code of this log or channel. Example: 'Neutron Porosity' for 'Thermal Neutron Porosity Sandstone'. (optional)",
        title='Log Family Type',
    )
    format: Optional[Format_2] = Field(
        'float32',
        description="Optional format hint how to treat the log values as strings or number of bits per 'dataType'.",
        title='Format Hint',
    )
    logstoreId: Optional[float] = Field(
        None,
        description='The unique id of this log or channel in the Logstore. This property is not present in the index channel.',
        title='Logstore ID',
    )
    bulkURI: Optional[str] = Field(
        None,
        description='bulkURI either URL or URN.',
        title='bulk URI',
    )
    longName: Optional[str] = Field(
        None, description='The long name of this log or channel', title='Log Long Name'
    )
    mnemonic: Optional[str] = Field(
        None, description='The mnemonic of this log or channel', title='Mnemonic'
    )
    name: Optional[str] = Field(
        None, description='The name of this log or channel.', title='Log Name'
    )
    properties: Optional[List[namedProperty]] = Field(
        None,
        description='The named properties of this log or channel.',
        title='Named Properties',
    )
    source: Optional[str] = Field(
        None,
        description='The source of this log or channel as a data reference; Typically this refers to the raw LogSet, from which this log WKE is generated.',
        title='Source',
    )
    unitKey: Optional[str] = Field(
        None,
        description="The unitKey to be looked up in the 'frameOfReference.units' dictionary to find the self-contained definition.",
        title='Unit',
    )


class logData(DDMSBaseModelWithExtra):
    azimuthReference: Optional[str] = Field(
        None,
        description='Only supplied with azimuth logs: the azimuth reference code defining the type of North, default TN for true north.',
        title='Azimuth Reference Code',
    )
    dateCreated: Optional[datetime] = Field(
        None,
        description='The UTC date time of the entity creation',
        title='Creation Date and Time',
    )
    dateModified: Optional[datetime] = Field(
        None,
        description='The UTC date time of the last entity modification',
        title='Last Modification Date and Time',
    )
    elevationReference: Optional[SimpleElevationReference] = Field(
        None,
        description="The wellbore's elevation reference from mean sea level (MSL), positive above MSL. This is where the index, e.g. MD == 0 and TVD == 0.",
        title='Elevation Reference',
    )
    externalIds: Optional[List[str]] = Field(
        None,
        description='An array of identities (e.g. some kind if URL to be resolved in an external data store), which links to external realizations of the same entity.',
        title='Array of External IDs',
    )
    history: Optional[List[historyRecord]] = Field(
        None,
        description="An array of historyRecords describing the context for the log's creation or processing.",
        title='History Records',
    )
    log: Optional[logchannel] = Field(
        None,
        description='The log containing the log meta data and log-store reference.',
        title='Log Channel',
    )
    name: Optional[str] = Field(
        None, description='The name of this log set', title='Log Set Name'
    )
    operation: Optional[str] = Field(
        None, description='The operation which created this Log', title='Operation'
    )
    reference: Optional[logchannel] = Field(
        None,
        description='The reference index - only populated for logs, which are member of a logSet and share the reference index.',
        title='Reference Index',
    )
    referenceType: Optional[ReferenceType] = Field(
        None, description='The reference index type of the log set.', title='Index Type'
    )
    relationships: Optional[logRelationships] = Field(
        None, description='The related entities.', title='Relationships'
    )
    start: Optional[ValueWithUnit] = Field(
        None, description='The start index value of the log set.', title='Start'
    )
    step: Optional[ValueWithUnit] = Field(
        None,
        description='The index increment value of the log set. Only populated if the log is regularly sampled.',
        title='Step',
    )
    stop: Optional[ValueWithUnit] = Field(
        None, description='The stop index value of the log set.', title='Stop'
    )


class log(DDMSBaseModel, DDMSBaseRecord):
    acl: Optional[TagDictionary] = Field(
        None,
        description='The access control tags associated with this entity.',
        title='Access Control List',
    )
    data: Optional[logData] = Field(
        None, description='Log data associated with a wellbore', title='Log Data'
    )
    id: Optional[str] = Field(
        None, description='The unique identifier of the log', title='Log Set ID'
    )
    kind: Optional[str] = Field(
        'osdu:wks:log:0.0.1', description='Kind specification', title='Log Kind'
    )
    legal: Optional[Legal] = Field(
        None, description="The log's legal tags", title='Legal Tags'
    )
    status: Optional[str] = Field(
        'compliant', description='The status of this log', title='Entity Status'
    )
    version: Optional[float] = Field(
        None,
        description='The version number of this log; set by the framework.',
        title='Entity Version Number',
    )


class dipSetData(DDMSBaseModelWithExtra):
    azimuthReference: Optional[str] = Field(
        None,
        description='Azimuth reference code defining the type of North. Only used for dipSets with azimuth data',
        title='Azimuth Reference Code',
    )
    classification: Optional[str] = Field(
        'Externally Processed LogSet',
        description='The well-known log set classification code.',
        title='Log Set Classification',
    )
    dateCreated: Optional[datetime] = Field(
        None,
        description='The UTC date time of the entity creation',
        title='Creation Date and Time',
    )
    dateModified: Optional[datetime] = Field(
        None,
        description='The UTC date time of the last entity modification',
        title='Last Modification Date and Time',
    )
    elevationReference: Optional[SimpleElevationReference] = None
    externalIds: Optional[List[str]] = Field(
        None,
        description='An array of identities (e.g. some kind if URL to be resolved in an external data store), which links to external realizations of the same entity.',
        title='Array of External IDs',
    )
    name: Optional[str] = Field(
        None, description='The name of this dip set', title='Dip Set Name'
    )
    operation: Optional[str] = Field(
        None, description='The operation which created this entity', title='Operation'
    )
    reference: Optional[channel] = None
    referenceType: Optional[str] = Field(
        None,
        description='The reference index type of the dip set.',
        title='Reference Type',
    )
    relationships: Optional[dipsetrelationships] = None
    start: Optional[ValueWithUnit] = None
    step: Optional[ValueWithUnit] = None
    stop: Optional[ValueWithUnit] = None
    bulkURI: Optional[str] = Field(
        None,
        description='bulkURI either URL or URN.',
        title='bulk URI',
    )


class dipset(DDMSBaseModel, DDMSBaseRecord):
    acl: Optional[TagDictionary] = Field(
        None,
        description='The access control tags associated with this entity.',
        title='Access Control List',
    )
    data: Optional[dipSetData] = Field(
        None,
        description='dipset data',
        title='Dip Set Data',
    )
    id: Optional[str] = Field(
        None, description='The unique identifier of the dip set', title='Dip Set ID'
    )
    kind: Optional[str] = Field(
        'osdu:wks:dipSet:1.0.0', description='Kind specification', title='Dip Set Kind'
    )
    legal: Optional[Legal] = Field(
        None, description="The dip-set's legal tags", title='Legal Tags'
    )
    version: Optional[float] = Field(
        None,
        description='The version number of this dip set; set by the framework.',
        title='Entity Version Number',
    )
