# Copyright 2021 Schlumberger
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen:
#   filename:  model

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Extra, Field, constr


class Tags(BaseModel):
    class Config:
        extra = Extra.allow

    __root__: str


class LogServiceDateInterval(BaseModel):
    """
    An interval built from two nested values : StartDate and EndDate. It applies to the whole log services and may apply to composite logs as [start of the first run job] and [end of the last run job]Log Service Date
    """

    StartDate: Optional[datetime] = None
    EndDate: Optional[datetime] = None


class Owner(BaseModel):
    __root__: constr(
        regex=r'^[a-zA-Z0-9_+&*-]+(?:\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,7}$'
    )


class Viewer(Owner):
    pass


class AbstractAccessControlList100(BaseModel):
    """
    The access control tags associated with this entity.
    """

    owners: List[Owner] = Field(
        ...,
        description='The list of owners of this data record formatted as an email (core.common.model.storage.validation.ValidationDoc.EMAIL_REGEX).',
        title='List of Owners',
    )
    viewers: List[Viewer] = Field(
        ...,
        description='The list of viewers to which this data record is accessible/visible/discoverable formatted as an email (core.common.model.storage.validation.ValidationDoc.EMAIL_REGEX).',
        title='List of Viewers',
    )


class AbstractAliasNames100(BaseModel):
    """
    A list of alternative names for an object.  The preferred name is in a separate, scalar property.  It may or may not be repeated in the alias list, though a best practice is to include it if the list is present, but to omit the list if there are no other names.  Note that the abstract entity is an array so the $ref to it is a simple property reference.
    """

    AliasName: Optional[str] = Field(
        None, description='Alternative Name value of defined name type for an object.'
    )
    AliasNameTypeID: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-AliasNameType:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='A classification of alias names such as by role played or type of source, such as regulatory name, regulatory code, company code, international standard name, etc.',
    )
    DefinitionOrganisationID: Optional[
        constr(
            regex=r'^[\w\-\.]+:(reference-data\-\-StandardsOrganisation|master-data\-\-Organisation):[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='The StandardsOrganisation (reference-data) or Organisation (master-data) that provided the name (the source).',
    )
    EffectiveDateTime: Optional[datetime] = Field(
        None, description='The date and time when an alias name becomes effective.'
    )
    TerminationDateTime: Optional[datetime] = Field(
        None, description='The data and time when an alias name is no longer in effect.'
    )


class Type(Enum):
    AnyCrsFeatureCollection = 'AnyCrsFeatureCollection'


class Type1(Enum):
    AnyCrsFeature = 'AnyCrsFeature'


class Type2(Enum):
    AnyCrsPoint = 'AnyCrsPoint'


class GeometryItem(BaseModel):
    type: Type2
    coordinates: List[float] = Field(..., min_items=2)
    bbox: Optional[List[float]] = Field(None, min_items=4)


class Type3(Enum):
    AnyCrsLineString = 'AnyCrsLineString'


class Coordinate(BaseModel):
    __root__: List[Any]


class GeometryItem1(BaseModel):
    type: Type3
    coordinates: List[Coordinate] = Field(..., min_items=2)
    bbox: Optional[List[float]] = Field(None, min_items=4)


class Type4(Enum):
    AnyCrsPolygon = 'AnyCrsPolygon'


class Coordinate1(Coordinate):
    pass


class GeometryItem2(BaseModel):
    type: Type4
    coordinates: List[Coordinate1]
    bbox: Optional[List[float]] = Field(None, min_items=4)


class Type5(Enum):
    AnyCrsMultiPoint = 'AnyCrsMultiPoint'


class Coordinate2(Coordinate):
    pass


class GeometryItem3(BaseModel):
    type: Type5
    coordinates: List[Coordinate2]
    bbox: Optional[List[float]] = Field(None, min_items=4)


class Type6(Enum):
    AnyCrsMultiLineString = 'AnyCrsMultiLineString'


class Coordinate3(Coordinate):
    pass


class GeometryItem4(BaseModel):
    type: Type6
    coordinates: List[Coordinate3]
    bbox: Optional[List[float]] = Field(None, min_items=4)


class Type7(Enum):
    AnyCrsMultiPolygon = 'AnyCrsMultiPolygon'


class Coordinate4(Coordinate):
    pass


class GeometryItem5(BaseModel):
    type: Type7
    coordinates: List[List[Coordinate4]]
    bbox: Optional[List[float]] = Field(None, min_items=4)


class Type8(Enum):
    AnyCrsGeometryCollection = 'AnyCrsGeometryCollection'


class GeometryItem6(BaseModel):
    type: Type8
    geometries: List[Any]
    bbox: Optional[List[float]] = Field(None, min_items=4)


class Feature(BaseModel):
    type: Type1
    properties: Optional[Dict[str, Any]]
    geometry: Optional[
        Union[
            GeometryItem,
            GeometryItem1,
            GeometryItem2,
            GeometryItem3,
            GeometryItem4,
            GeometryItem5,
            GeometryItem6,
        ]
    ]
    bbox: Optional[List[float]] = Field(None, min_items=4)


class AbstractAnyCrsFeatureCollection100(BaseModel):
    """
    The original or 'as ingested' coordinates (Point, MultiPoint, LineString, MultiLineString, Polygon or MultiPolygon). The name 'AsIngestedCoordinates' was chosen to contrast it to 'OriginalCoordinates', which carries the uncertainty whether any coordinate operations took place before ingestion. In cases where the original CRS is different from the as-ingested CRS, the OperationsApplied can also contain the list of operations applied to the coordinate prior to ingestion. The data structure is similar to GeoJSON FeatureCollection, however in a CRS context explicitly defined within the AbstractAnyCrsFeatureCollection. The coordinate sequence follows GeoJSON standard, i.e. 'eastward/longitude', 'northward/latitude' {, 'upward/height' unless overridden by an explicit direction in the AsIngestedCoordinates.VerticalCoordinateReferenceSystemID}.
    """

    type: Type
    CoordinateReferenceSystemID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-CoordinateReferenceSystem:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='The CRS reference into the CoordinateReferenceSystem catalog.',
        example='namespace:reference-data--CoordinateReferenceSystem:BoundCRS.SLB.32021.15851:',
        title='Coordinate Reference System ID',
    )
    VerticalCoordinateReferenceSystemID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-CoordinateReferenceSystem:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description="The explicit VerticalCRS reference into the CoordinateReferenceSystem catalog. This property stays empty for 2D geometries. Absent or empty values for 3D geometries mean the context may be provided by a CompoundCRS in 'CoordinateReferenceSystemID' or implicitly EPSG:5714 MSL height",
        example='namespace:reference-data--CoordinateReferenceSystem:VerticalCRS.EPSG.5773:',
        title='Vertical Coordinate Reference System ID',
    )
    persistableReferenceCrs: str = Field(
        ...,
        description='The CRS reference as persistableReference string. If populated, the CoordinateReferenceSystemID takes precedence.',
        example='{"lateBoundCRS":{"wkt":"PROJCS[\\"NAD_1927_StatePlane_North_Dakota_South_FIPS_3302\\",GEOGCS[\\"GCS_North_American_1927\\",DATUM[\\"D_North_American_1927\\",SPHEROID[\\"Clarke_1866\\",6378206.4,294.9786982]],PRIMEM[\\"Greenwich\\",0.0],UNIT[\\"Degree\\",0.0174532925199433]],PROJECTION[\\"Lambert_Conformal_Conic\\"],PARAMETER[\\"False_Easting\\",2000000.0],PARAMETER[\\"False_Northing\\",0.0],PARAMETER[\\"Central_Meridian\\",-100.5],PARAMETER[\\"Standard_Parallel_1\\",46.1833333333333],PARAMETER[\\"Standard_Parallel_2\\",47.4833333333333],PARAMETER[\\"Latitude_Of_Origin\\",45.6666666666667],UNIT[\\"Foot_US\\",0.304800609601219],AUTHORITY[\\"EPSG\\",32021]]","ver":"PE_10_3_1","name":"NAD_1927_StatePlane_North_Dakota_South_FIPS_3302","authCode":{"auth":"EPSG","code":"32021"},"type":"LBC"},"singleCT":{"wkt":"GEOGTRAN[\\"NAD_1927_To_WGS_1984_79_CONUS\\",GEOGCS[\\"GCS_North_American_1927\\",DATUM[\\"D_North_American_1927\\",SPHEROID[\\"Clarke_1866\\",6378206.4,294.9786982]],PRIMEM[\\"Greenwich\\",0.0],UNIT[\\"Degree\\",0.0174532925199433]],GEOGCS[\\"GCS_WGS_1984\\",DATUM[\\"D_WGS_1984\\",SPHEROID[\\"WGS_1984\\",6378137.0,298.257223563]],PRIMEM[\\"Greenwich\\",0.0],UNIT[\\"Degree\\",0.0174532925199433]],METHOD[\\"NADCON\\"],PARAMETER[\\"Dataset_conus\\",0.0],AUTHORITY[\\"EPSG\\",15851]]","ver":"PE_10_3_1","name":"NAD_1927_To_WGS_1984_79_CONUS","authCode":{"auth":"EPSG","code":"15851"},"type":"ST"},"ver":"PE_10_3_1","name":"NAD27 * OGP-Usa Conus / North Dakota South [32021,15851]","authCode":{"auth":"SLB","code":"32021079"},"type":"EBC"}',
        title='CRS Reference',
    )
    persistableReferenceVerticalCrs: Optional[str] = Field(
        None,
        description="The VerticalCRS reference as persistableReference string. If populated, the VerticalCoordinateReferenceSystemID takes precedence. The property is null or empty for 2D geometries. For 3D geometries and absent or null persistableReferenceVerticalCrs the vertical CRS is either provided via persistableReferenceCrs's CompoundCRS or it is implicitly defined as EPSG:5714 MSL height.",
        example='{"authCode":{"auth":"EPSG","code":"5773"},"type":"LBC","ver":"PE_10_3_1","name":"EGM96_Geoid","wkt":"VERTCS[\\"EGM96_Geoid\\",VDATUM[\\"EGM96_Geoid\\"],PARAMETER[\\"Vertical_Shift\\",0.0],PARAMETER[\\"Direction\\",1.0],UNIT[\\"Meter\\",1.0],AUTHORITY[\\"EPSG\\",5773]]"}',
        title='Vertical CRS Reference',
    )
    persistableReferenceUnitZ: Optional[str] = Field(
        None,
        description='The unit of measure for the Z-axis (only for 3-dimensional coordinates, where the CRS does not describe the vertical unit). Note that the direction is upwards positive, i.e. Z means height.',
        example='{"scaleOffset":{"scale":1.0,"offset":0.0},"symbol":"m","baseMeasurement":{"ancestry":"Length","type":"UM"},"type":"USO"}',
        title='Z-Unit Reference',
    )
    features: List[Feature]
    bbox: Optional[List[float]] = Field(None, min_items=4)


class ResourceHostRegionID(BaseModel):
    __root__: constr(
        regex=r'^[\w\-\.]+:reference-data\-\-OSDURegion:[\w\-\.\:\%]+:[0-9]*$'
    )


class AbstractCommonResources100(BaseModel):
    """
    Common resources to be injected at root 'data' level for every entity, which is persistable in Storage. The insertion is performed by the OsduSchemaComposer script.
    """

    ResourceHomeRegionID: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-OSDURegion:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='The name of the home [cloud environment] region for this OSDU resource object.',
        title='Resource Home Region ID',
    )
    ResourceHostRegionIDs: Optional[List[ResourceHostRegionID]] = Field(
        None,
        description='The name of the host [cloud environment] region(s) for this OSDU resource object.',
        title='Resource Host Region ID',
    )
    ResourceCurationStatus: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-ResourceCurationStatus:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='Describes the current Curation status.',
        title='Resource Curation Status',
    )
    ResourceLifecycleStatus: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-ResourceLifecycleStatus:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='Describes the current Resource Lifecycle status.',
        title='Resource Lifecycle Status',
    )
    ResourceSecurityClassification: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-ResourceSecurityClassification:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='Classifies the security level of the resource.',
        title='Resource Security Classification',
    )
    Source: Optional[str] = Field(
        None,
        description='The entity that produced the record, or from which it is received; could be an organization, agency, system, internal team, or individual. For informational purposes only, the list of sources is not governed.',
        title='Data Source',
    )
    ExistenceKind: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-ExistenceKind:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='Where does this data resource sit in the cradle-to-grave span of its existence?',
        title='Existence Kind',
    )


class AbstractFacilityEvent100(BaseModel):
    """
    A significant occurrence in the life of a facility, which often changes its state, or the state of one of its components. It can describe a point-in-time (event) or a time interval of a specific type (FacilityEventType).
    """

    FacilityEventTypeID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-FacilityEventType:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description="The facility event type is a picklist. Examples: 'Permit', 'Spud', 'Abandon', etc.",
    )
    EffectiveDateTime: Optional[datetime] = Field(
        None,
        description='The date and time at which the event took place or takes effect.',
    )
    TerminationDateTime: Optional[datetime] = Field(
        None,
        description="The date and time at which the event is no longer in effect. For point-in-time events the 'TerminationDateTime' must be set equal to 'EffectiveDateTime'. Open time intervals have an absent 'TerminationDateTime'.",
    )


class AbstractFacilityOperator100(BaseModel):
    """
    The organisation that was responsible for a facility at some point in time.
    """

    FacilityOperatorID: Optional[str] = Field(
        None,
        description="Internal, unique identifier for an item 'AbstractFacilityOperator'. This identifier is used by 'AbstractFacility.CurrentOperatorID' and 'AbstractFacility.InitialOperatorID'.",
        title='Facility Operator ID',
    )
    FacilityOperatorOrganisationID: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-Organisation:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='The company that currently operates, or previously operated the facility',
    )
    EffectiveDateTime: Optional[datetime] = Field(
        None,
        description='The date and time at which the facility operator becomes effective.',
    )
    TerminationDateTime: Optional[datetime] = Field(
        None,
        description="The date and time at which the facility operator is no longer in effect. If the operator is still effective, the 'TerminationDateTime' is left absent.",
    )


class AbstractFacilitySpecification100(BaseModel):
    """
    A property, characteristic, or attribute about a facility that is not described explicitly elsewhere.
    """

    EffectiveDateTime: Optional[datetime] = Field(
        None,
        description='The date and time at which the facility specification instance becomes effective.',
    )
    TerminationDateTime: Optional[datetime] = Field(
        None,
        description='The date and time at which the facility specification instance is no longer in effect.',
    )
    FacilitySpecificationQuantity: Optional[float] = Field(
        None, description='The value for the specified parameter type.'
    )
    FacilitySpecificationDateTime: Optional[datetime] = Field(
        None, description='The actual date and time value of the parameter.'
    )
    FacilitySpecificationIndicator: Optional[bool] = Field(
        None, description='The actual indicator value of the parameter.'
    )
    FacilitySpecificationText: Optional[str] = Field(
        None, description='The actual text value of the parameter.'
    )
    UnitOfMeasureID: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='The unit for the quantity parameter, like metre (m in SI units system) for quantity Length.',
    )
    ParameterTypeID: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-ParameterType:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(None, description='Parameter type of property or characteristic.')


class AbstractFacilityState100(BaseModel):
    """
    The life cycle status of a facility at some point in time.
    """

    EffectiveDateTime: Optional[datetime] = Field(
        None,
        description='The date and time at which the facility state becomes effective.',
    )
    TerminationDateTime: Optional[datetime] = Field(
        None,
        description='The date and time at which the facility state is no longer in effect.',
    )
    FacilityStateTypeID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-FacilityStateType:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None, description='The facility life cycle state from planning to abandonment.'
    )


class AbstractFacilityVerticalMeasurement100(BaseModel):
    """
    A location along a wellbore, _usually_ associated with some aspect of the drilling of the wellbore, but not with any intersecting _subsurface_ natural surfaces.
    """

    EffectiveDateTime: Optional[datetime] = Field(
        None,
        description='The date and time at which a vertical measurement instance becomes effective.',
    )
    VerticalMeasurement: Optional[float] = Field(
        None,
        description='The value of the elevation or depth. Depth is positive downwards from a vertical reference or geodetic datum along a path, which can be vertical; elevation is positive upwards from a geodetic datum along a vertical path. Either can be negative.',
    )
    TerminationDateTime: Optional[datetime] = Field(
        None,
        description='The date and time at which a vertical measurement instance is no longer in effect.',
    )
    VerticalMeasurementTypeID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-VerticalMeasurementType:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='Specifies the type of vertical measurement (TD, Plugback, Kickoff, Drill Floor, Rotary Table...).',
    )
    VerticalMeasurementPathID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-VerticalMeasurementPath:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None, description='Specifies Measured Depth, True Vertical Depth, or Elevation.'
    )
    VerticalMeasurementSourceID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-VerticalMeasurementSource:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(None, description='Specifies Driller vs Logger.')
    WellboreTVDTrajectoryID: Optional[
        constr(
            regex=r'^[\w\-\.]+:work-product-component\-\-WellboreTrajectory:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='Specifies what directional survey or wellpath was used to calculate the TVD.',
    )
    VerticalMeasurementUnitOfMeasureID: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='The unit of measure for the vertical measurement. If a unit of measure and a vertical CRS are provided, the unit of measure provided is taken over the unit of measure from the CRS.',
    )
    VerticalCRSID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-CoordinateReferenceSystem:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='A vertical coordinate reference system defines the origin for height or depth values. It is expected that either VerticalCRSID or VerticalReferenceID reference is provided in a given vertical measurement array object, but not both.',
    )
    VerticalReferenceID: Optional[str] = Field(
        None,
        description='The reference point from which the relative vertical measurement is made. This is only populated if the measurement has no VerticalCRSID specified. The value entered must be the VerticalMeasurementID for another vertical measurement array element in this resource or its parent facility, and as a chain of measurements, they must resolve ultimately to a Vertical CRS. It is expected that a VerticalCRSID or a VerticalReferenceID is provided in a given vertical measurement array object, but not both.',
    )
    VerticalMeasurementDescription: Optional[str] = Field(
        None, description='Text which describes a vertical measurement in detail.'
    )


class Type9(Enum):
    FeatureCollection = 'FeatureCollection'


class Type10(Enum):
    Feature = 'Feature'


class Type11(Enum):
    Point = 'Point'


class GeometryItem7(BaseModel):
    type: Type11
    coordinates: List[float] = Field(..., min_items=2)
    bbox: Optional[List[float]] = Field(None, min_items=4)


class Type12(Enum):
    LineString = 'LineString'


class Coordinate5(Coordinate):
    pass


class GeometryItem8(BaseModel):
    type: Type12
    coordinates: List[Coordinate5] = Field(..., min_items=2)
    bbox: Optional[List[float]] = Field(None, min_items=4)


class Type13(Enum):
    Polygon = 'Polygon'


class Coordinate6(Coordinate):
    pass


class GeometryItem9(BaseModel):
    type: Type13
    coordinates: List[Coordinate6]
    bbox: Optional[List[float]] = Field(None, min_items=4)


class Type14(Enum):
    MultiPoint = 'MultiPoint'


class Coordinate7(Coordinate):
    pass


class GeometryItem10(BaseModel):
    type: Type14
    coordinates: List[Coordinate7]
    bbox: Optional[List[float]] = Field(None, min_items=4)


class Type15(Enum):
    MultiLineString = 'MultiLineString'


class Coordinate8(Coordinate):
    pass


class GeometryItem11(BaseModel):
    type: Type15
    coordinates: List[Coordinate8]
    bbox: Optional[List[float]] = Field(None, min_items=4)


class Type16(Enum):
    MultiPolygon = 'MultiPolygon'


class Coordinate9(Coordinate):
    pass


class GeometryItem12(BaseModel):
    type: Type16
    coordinates: List[List[Coordinate9]]
    bbox: Optional[List[float]] = Field(None, min_items=4)


class Type17(Enum):
    GeometryCollection = 'GeometryCollection'


class GeometryItem13(BaseModel):
    type: Type17
    geometries: List[Any]
    bbox: Optional[List[float]] = Field(None, min_items=4)


class Feature1(BaseModel):
    type: Type10
    properties: Optional[Dict[str, Any]]
    geometry: Optional[
        Union[
            GeometryItem7,
            GeometryItem8,
            GeometryItem9,
            GeometryItem10,
            GeometryItem11,
            GeometryItem12,
            GeometryItem13,
        ]
    ]
    bbox: Optional[List[float]] = Field(None, min_items=4)


class AbstractFeatureCollection100(BaseModel):
    """
    The normalized coordinates (Point, MultiPoint, LineString, MultiLineString, Polygon or MultiPolygon) based on WGS 84 (EPSG:4326 for 2-dimensional coordinates, EPSG:4326 + EPSG:5714 (MSL) for 3-dimensional coordinates). This derived coordinate representation is intended for global discoverability only. The schema of this substructure is identical to the GeoJSON FeatureCollection https://geojson.org/schema/FeatureCollection.json. The coordinate sequence follows GeoJSON standard, i.e. longitude, latitude {, height}
    """

    type: Type9
    features: List[Feature1]
    bbox: Optional[List[float]] = Field(None, min_items=4)


class AbstractGeoBasinContext100(BaseModel):
    """
    A single, typed basin entity reference, which is 'abstracted' to AbstractGeoContext and then aggregated by GeoContexts properties.
    """

    BasinID: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-Basin:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(None, description='Reference to Basin.')
    GeoTypeID: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-BasinType:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='The BasinType reference of the Basin (via BasinID) for application convenience.',
    )


class AbstractGeoFieldContext100(BaseModel):
    """
    A single, typed field entity reference, which is 'abstracted' to AbstractGeoContext and then aggregated by GeoContexts properties.
    """

    FieldID: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-Field:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(None, description='Reference to Field.')
    GeoTypeID: Optional[Any] = Field(
        None, description="The fixed type 'Field' for this AbstractGeoFieldContext."
    )


class AbstractGeoPlayContext100(BaseModel):
    """
    A single, typed Play entity reference, which is 'abstracted' to AbstractGeoContext and then aggregated by GeoContexts properties.
    """

    PlayID: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-Play:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(None, description='Reference to the play.')
    GeoTypeID: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-PlayType:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='The PlayType reference of the Play (via PlayID) for application convenience.',
    )


class AbstractGeoPoliticalContext100(BaseModel):
    """
    A single, typed geo-political entity reference, which is 'abstracted' to AbstractGeoContext and then aggregated by GeoContexts properties.
    """

    GeoPoliticalEntityID: Optional[
        constr(
            regex=r'^[\w\-\.]+:master-data\-\-GeoPoliticalEntity:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(None, description='Reference to GeoPoliticalEntity.')
    GeoTypeID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-GeoPoliticalEntityType:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='The GeoPoliticalEntityType reference of the GeoPoliticalEntity (via GeoPoliticalEntityID) for application convenience.',
    )


class AbstractGeoProspectContext100(BaseModel):
    """
    A single, typed Prospect entity reference, which is 'abstracted' to AbstractGeoContext and then aggregated by GeoContexts properties.
    """

    ProspectID: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-Prospect:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(None, description='Reference to the prospect.')
    GeoTypeID: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-ProspectType:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='The ProspectType reference of the Prospect (via ProspectID) for application convenience.',
    )


class Parent(BaseModel):
    __root__: constr(regex=r'^[\w\-\.]+:[\w\-\.]+:[\w\-\.\:\%]+:[0-9]+$')


class AbstractLegalParentList100(BaseModel):
    """
    The links to data, which constitute the inputs.
    """

    parents: Optional[List[Parent]] = Field(
        None,
        description="An array of none, one or many entity references in the data ecosystem, which identify the source of data in the legal sense. In contract to other relationships, the source record version is required. Example: the 'parents' will be queried when e.g. the subscription of source data services is terminated; access to the derivatives is also terminated.",
        example=[],
        title='Parents',
    )


class OtherRelevantDataCountry(BaseModel):
    __root__: constr(regex=r'^[A-Z]{2}$')


class AbstractLegalTags100(BaseModel):
    """
    The entity's legal tags and compliance status. The actual contents associated with the legal tags is managed by the Compliance Service.
    """

    legaltags: List[str] = Field(
        ...,
        description='The list of legal tags, which resolve to legal properties (like country of origin, export classification code, etc.) and rules with the help of the Compliance Service.',
        title='Legal Tags',
    )
    otherRelevantDataCountries: List[OtherRelevantDataCountry] = Field(
        ...,
        description='The list of other relevant data countries as an array of two-letter country codes, see https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2.',
        title='Other Relevant Data Countries',
    )
    status: Optional[constr(regex=r'^(compliant|uncompliant)$')] = Field(
        None,
        description='The legal status. Set by the system after evaluation against the compliance rules associated with the "legaltags" using the Compliance Service.',
        title='Legal Status',
    )


class AbstractSpatialLocation100(BaseModel):
    """
    The spatial location information such as coordinates, CRS information (left empty when not appropriate).
    """

    SpatialLocationCoordinatesDate: Optional[datetime] = Field(
        None, description='Date when coordinates were measured or retrieved.'
    )
    QuantitativeAccuracyBandID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-QuantitativeAccuracyBand:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='An approximate quantitative assessment of the quality of a location (accurate to > 500 m (i.e. not very accurate)), to < 1 m, etc.',
    )
    QualitativeSpatialAccuracyTypeID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-QualitativeSpatialAccuracyType:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='A qualitative description of the quality of a spatial location, e.g. unverifiable, not verified, basic validation.',
    )
    CoordinateQualityCheckPerformedBy: Optional[str] = Field(
        None, description='The user who performed the Quality Check.'
    )
    CoordinateQualityCheckDateTime: Optional[datetime] = Field(
        None, description='The date of the Quality Check.'
    )
    CoordinateQualityCheckRemarks: Optional[List[str]] = Field(
        None, description='Freetext remarks on Quality Check.'
    )
    AsIngestedCoordinates: Optional[AbstractAnyCrsFeatureCollection100] = Field(
        None,
        description="The original or 'as ingested' coordinates (Point, MultiPoint, LineString, MultiLineString, Polygon or MultiPolygon). The name 'AsIngestedCoordinates' was chosen to contrast it to 'OriginalCoordinates', which carries the uncertainty whether any coordinate operations took place before ingestion. In cases where the original CRS is different from the as-ingested CRS, the OperationsApplied can also contain the list of operations applied to the coordinate prior to ingestion. The data structure is similar to GeoJSON FeatureCollection, however in a CRS context explicitly defined within the AbstractAnyCrsFeatureCollection. The coordinate sequence follows GeoJSON standard, i.e. 'eastward/longitude', 'northward/latitude' {, 'upward/height' unless overridden by an explicit direction in the AsIngestedCoordinates.VerticalCoordinateReferenceSystemID}.",
        title='As Ingested Coordinates',
    )
    Wgs84Coordinates: Optional[AbstractFeatureCollection100] = Field(
        None,
        description='The normalized coordinates (Point, MultiPoint, LineString, MultiLineString, Polygon or MultiPolygon) based on WGS 84 (EPSG:4326 for 2-dimensional coordinates, EPSG:4326 + EPSG:5714 (MSL) for 3-dimensional coordinates). This derived coordinate representation is intended for global discoverability only. The schema of this substructure is identical to the GeoJSON FeatureCollection https://geojson.org/schema/FeatureCollection.json. The coordinate sequence follows GeoJSON standard, i.e. longitude, latitude {, height}',
        title='WGS 84 Coordinates',
    )
    AppliedOperations: Optional[List[str]] = Field(
        None,
        description='The audit trail of operations applied to the coordinates from the original state to the current state. The list may contain operations applied prior to ingestion as well as the operations applied to produce the Wgs84Coordinates. The text elements refer to ESRI style CRS and Transformation names, which may have to be translated to EPSG standard names.',
        example=[
            'conversion from ED_1950_UTM_Zone_31N to GCS_European_1950; 1 points converted',
            'transformation GCS_European_1950 to GCS_WGS_1984 using ED_1950_To_WGS_1984_24; 1 points successfully transformed',
        ],
        title='Operations Applied',
    )
    SpatialParameterTypeID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-SpatialParameterType:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='A type of spatial representation of an object, often general (e.g. an Outline, which could be applied to Field, Reservoir, Facility, etc.) or sometimes specific (e.g. Onshore Outline, State Offshore Outline, Federal Offshore Outline, 3 spatial representations that may be used by Countries).',
    )
    SpatialGeometryTypeID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-SpatialGeometryType:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='Indicates the expected look of the SpatialParameterType, e.g. Point, MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon. The value constrains the type of geometries in the GeoJSON Wgs84Coordinates and AsIngestedCoordinates.',
    )


class Dataset(BaseModel):
    __root__: constr(
        regex=r'^[\w\-\.]+:dataset\-\-[\w\-\.]+:[\w\-\.\:\%]+:[0-9]*$'
    ) = Field(..., description='The SRN which identifies this OSDU File resource.')


class Artefact(BaseModel):
    RoleID: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-ArtefactRole:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(None, description="The SRN of this artefact's role.")
    ResourceKind: Optional[
        constr(regex=r'^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$')
    ] = Field(
        None,
        description='The kind or schema ID of the artefact. Resolvable with the Schema Service.',
    )
    ResourceID: Optional[
        constr(regex=r'^[\w\-\.]+:dataset\-\-[\w\-\.]+:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(None, description='The SRN which identifies this OSDU Artefact resource.')



class AbstractWellboreDrillingReason100(BaseModel):
    """
    Purpose for drilling a wellbore, which often is an indication of the level of risk.
    """

    DrillingReasonTypeID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-DrillingReasonType:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='Identifier of the drilling reason type for the corresponding time period.',
    )
    EffectiveDateTime: Optional[datetime] = Field(
        None, description='The date and time at which the event becomes effective.'
    )
    TerminationDateTime: Optional[datetime] = Field(
        None, description='The date and time at which the event is no longer in effect.'
    )


class AbstractFacility100(BaseModel):
    FacilityID: Optional[str] = Field(
        None, description='A system-specified unique identifier of a Facility.'
    )
    FacilityTypeID: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-FacilityType:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='The definition of a kind of capability to perform a business function or a service.',
    )
    FacilityOperators: Optional[List[AbstractFacilityOperator100]] = Field(
        None, description='The history of operator organizations of the facility.'
    )
    InitialOperatorID: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-Organisation:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='A initial operator organization ID; the organization ID may also be found in the FacilityOperatorOrganisationID of the FacilityOperator array providing the actual dates.',
        title='Initial Operator ID',
    )
    CurrentOperatorID: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-Organisation:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='The current operator organization ID; the organization ID may also be found in the FacilityOperatorOrganisationID of the FacilityOperator array providing the actual dates.',
        title='Current Operator ID',
    )
    DataSourceOrganisationID: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-Organisation:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(None, description='The main source of the header information.')
    OperatingEnvironmentID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-OperatingEnvironment:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description="Identifies the Facility's general location as being onshore vs. offshore.",
    )
    FacilityName: Optional[str] = Field(None, description='Name of the Facility.')
    FacilityNameAliases: Optional[List[AbstractAliasNames100]] = Field(
        None,
        description='Alternative names, including historical, by which this facility is/has been known.',
    )
    FacilityStates: Optional[List[AbstractFacilityState100]] = Field(
        None,
        description='The history of life cycle states the facility has been through.',
    )
    FacilityEvents: Optional[List[AbstractFacilityEvent100]] = Field(
        None, description='A list of key facility events.'
    )
    FacilitySpecifications: Optional[List[AbstractFacilitySpecification100]] = Field(
        None,
        description='facilitySpecification maintains the specification like slot name, wellbore drilling permit number, rig name etc.',
    )


class AbstractMaster100(BaseModel):
    """
    Properties shared with all master-data schema instances.
    """

    NameAliases: Optional[List[AbstractAliasNames100]] = Field(
        None,
        description='Alternative names, including historical, by which this master data is/has been known (it should include all the identifiers).',
    )
    GeoContexts: Optional[List[Any]] = Field(
        None,
        description='List of geographic entities which provide context to the master data. This may include multiple types or multiple values of the same type.',
    )
    SpatialLocation: Optional[AbstractSpatialLocation100] = Field(
        None,
        description='The spatial location information such as coordinates, CRS information (left empty when not appropriate).',
    )
    VersionCreationReason: Optional[str] = Field(
        None,
        description='This describes the reason that caused the creation of a new version of this master data.',
    )


class VerticalMeasurement(AbstractFacilityVerticalMeasurement100):
    VerticalMeasurementID: Optional[str] = Field(
        None,
        description='The ID for a distinct vertical measurement within the Wellbore VerticalMeasurements array so that it may be referenced by other vertical measurements if necessary.',
    )

class AbstractWPCGroupType100(BaseModel):
    """
    Generic reference object containing the universal group-type properties of a Work Product Component for inclusion in data type specific Work Product Component objects
    """

    Datasets: Optional[List[Dataset]] = None
    Artefacts: Optional[List[Artefact]] = Field(
        None,
        description='An array of Artefacts - each artefact has a Role, Resource tuple. An artefact is distinct from the file, in the sense certain valuable information is generated during loading process (Artefact generation process). Examples include retrieving location data, performing an OCR which may result in the generation of artefacts which need to be preserved distinctly',
    )
    IsExtendedLoad: Optional[bool] = Field(
        None,
        description='A flag that indicates if the work product component is undergoing an extended load.  It reflects the fact that the work product component is in an early stage and may be updated before finalization.',
    )
    IsDiscoverable: Optional[bool] = Field(
        None,
        description='A flag that indicates if the work product component is searchable, which means covered in the search index.',
    )


class LineageAssertion(BaseModel):
    ID: Optional[
        constr(regex=r'^[\w\-\.]+:[\w\-\.]+\-\-[\w\-\.]+:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='The object reference identifying the DIRECT, INDIRECT, REFERENCE dependency.',
    )
    LineageRelationshipType: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-LineageRelationshipType:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='Used by LineageAssertion to describe the nature of the line of descent of a work product component from a prior Resource, such as DIRECT, INDIRECT, REFERENCE.  It is not for proximity (number of nodes away), it is not to cover all the relationships in a full ontology or graph, and it is not to describe the type of activity that created the asserting WPC.  LineageAssertion does not encompass a full provenance, process history, or activity model.',
    )


class AbstractWorkProductComponent100(BaseModel):
    """
    Generic reference object containing the universal properties of a Work Product Component for inclusion in data type specific Work Product Component objects
    """

    Name: Optional[str] = Field(None, description='Name')
    Description: Optional[str] = Field(
        None,
        description='Description.  Summary of the work product component.  Not the same as Remark which captures thoughts of creator about the wpc.',
    )
    CreationDateTime: Optional[datetime] = Field(
        None,
        description='Date that a resource (work  product component here) is formed outside of OSDU before loading (e.g. publication date).',
    )
    Tags: Optional[List[str]] = Field(
        None,
        description='Array of key words to identify the work product, especially to help in search.',
    )
    SpatialPoint: Optional[AbstractSpatialLocation100] = Field(
        None,
        description='A centroid point that reflects the locale of the content of the work product component (location of the subject matter).',
    )
    SpatialArea: Optional[AbstractSpatialLocation100] = Field(
        None,
        description='A polygon boundary that reflects the locale of the content of the work product component (location of the subject matter).',
    )
    GeoContexts: Optional[List[Any]] = Field(
        None,
        description='List of geographic entities which provide context to the WPC.  This may include multiple types or multiple values of the same type.',
    )
    SubmitterName: Optional[str] = Field(
        None,
        description='Name of the person that first submitted the work product component to OSDU.',
    )
    BusinessActivities: Optional[List[str]] = Field(
        None,
        description='Array of business processes/workflows that the work product component has been through (ex. well planning, exploration).',
    )
    AuthorIDs: Optional[List[str]] = Field(
        None,
        description="Array of Authors' names of the work product component.  Could be a person or company entity.",
    )
    LineageAssertions: Optional[List[LineageAssertion]] = Field(
        None,
        description='Defines relationships with other objects (any kind of Resource) upon which this work product component depends.  The assertion is directed only from the asserting WPC to ancestor objects, not children.  It should not be used to refer to files or artefacts within the WPC -- the association within the WPC is sufficient and Artefacts are actually children of the main WPC file. They should be recorded in the Data.Artefacts[] array.',
    )


class Curve(BaseModel):
    CurveID: Optional[str] = Field(None, description='The ID of the Well Log Curve')
    DateStamp: Optional[datetime] = Field(
        None, description='Date curve was created in the database'
    )
    CurveVersion: Optional[str] = Field(
        None, description='The Version of the Log Curve.'
    )
    CurveQuality: Optional[str] = Field(
        None, description='The Quality of the Log Curve.'
    )
    InterpreterName: Optional[str] = Field(
        None, description='The name of person who interpreted this Log Curve.'
    )
    IsProcessed: Optional[bool] = Field(
        None,
        description='Indicates if the curve has been (pre)processed or if it is a raw recording',
    )
    NullValue: Optional[bool] = Field(
        None, description='Indicates that there is no measurement within the curve'
    )
    DepthCoding: Optional[constr(regex=r'^REGULAR|DISCRETE$')] = Field(
        None, description='The Coding of the depth.'
    )
    Interpolate: Optional[bool] = Field(
        None, description='Whether curve can be interpolated or not'
    )
    TopDepth: Optional[float] = Field(None, description='Top Depth')
    BaseDepth: Optional[float] = Field(None, description='Base Depth')
    DepthUnit: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(None, description='Unit of Measure for Top and Base depth')
    CurveUnit: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(None, description='Unit of Measure for the Log Curve')
    Mnemonic: Optional[str] = Field(
        None,
        description='The Mnemonic of the Log Curve is the value as received either from Raw Providers or from Internal Processing team ',
    )
    LogCurveTypeID: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-LogCurveType:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='The SRN of the Log Curve Type - which is the standard mnemonic chosen by the company - OSDU provides an initial list',
    )
    LogCurveBusinessValueID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-LogCurveBusinessValue:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(None, description='The SRN of the Log Curve Business Value Type.')
    LogCurveMainFamilyID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-LogCurveMainFamily:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='The SRN of the Log Curve Main Family Type - which is the Geological Physical Quantity measured - such as porosity.',
    )
    LogCurveFamilyID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-LogCurveFamily:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='The SRN of the Log Curve Family - which is the detailed Geological Physical Quantity Measured - such as neutron porosity',
    )
    VerticalMeasurement: Optional[AbstractFacilityVerticalMeasurement100] = Field(
        None,
        description='References an entry in the Vertical Measurement array for the Wellbore identified by WellboreID, which defines the vertical reference datum for the logged depths.',
    )


class WellData(AbstractCommonResources100, AbstractMaster100, AbstractFacility100):
    DefaultVerticalMeasurementID: Optional[str] = Field(
        None,
        description='The default datum reference point, or zero depth point, used to determine other points vertically in a well.  References an entry in the VerticalMeasurements array.',
    )
    DefaultVerticalCRSID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-CoordinateReferenceSystem:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='The default vertical coordinate reference system used in the vertical measurements for a well or wellbore if absent from input vertical measurements and there is no other recourse for obtaining a valid CRS.',
    )
    VerticalMeasurements: Optional[List[VerticalMeasurement]] = Field(
        None,
        description='List of all depths and elevations pertaining to the well, like, water depth, mud line elevation, etc.',
    )
    InterestTypeID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-WellInterestType:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='Pre-defined reasons for interest in the well or information about the well.',
    )
    ExtensionProperties: Optional[Dict[str, Any]] = None


class Well(BaseModel):
    """
    The origin of a set of wellbores.
    """

    id: Optional[constr(regex=r'^[\w\-\.]+:master-data\-\-Well:[\w\-\.\:\%]+$')] = Field(
        None,
        description='Previously called ResourceID or SRN which identifies this OSDU resource object without version.',
        example='namespace:master-data--Well:6c60ceb0-3521-57b7-9bd8-e1d7c9f66230',
        title='Entity ID',
    )
    kind: constr(regex=r'^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$') = Field(
        ...,
        description='The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.',
        example='osdu:wks:master-data--Well:1.0.0',
        title='Entity Kind',
    )
    version: Optional[int] = Field(
        None,
        description='The version number of this OSDU resource; set by the framework.',
        example=1562066009929332,
        title='Version Number',
    )
    acl: AbstractAccessControlList100 = Field(
        ...,
        description='The access control tags associated with this entity.',
        title='Access Control List',
    )
    legal: AbstractLegalTags100 = Field(
        ...,
        description="The entity's legal tags and compliance status. The actual contents associated with the legal tags is managed by the Compliance Service.",
        title='Legal Tags',
    )
    tags: Optional[Dict[str, Tags]] = Field(
        None,
        description='A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.',
        example={'NameOfKey': 'String value'},
        title='Tag Dictionary',
    )
    createTime: Optional[datetime] = Field(
        None,
        description='Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.',
        example='2020-12-16T11:46:20.163Z',
        title='Resource Object Creation DateTime',
    )
    createUser: Optional[str] = Field(
        None,
        description='The user reference, which created the first version of this resource object. Set by the System.',
        example='some-user@some-company-cloud.com',
        title='Resource Object Creation User Reference',
    )
    modifyTime: Optional[datetime] = Field(
        None,
        description='Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.',
        example='2020-12-16T11:52:24.477Z',
        title='Resource Object Version Creation DateTime',
    )
    modifyUser: Optional[str] = Field(
        None,
        description='The user reference, which created this version of this resource object. Set by the System.',
        example='some-user@some-company-cloud.com',
        title='Resource Object Version Creation User Reference',
    )
    ancestry: Optional[AbstractLegalParentList100] = Field(
        None,
        description='The links to data, which constitute the inputs.',
        title='Ancestry',
    )
    meta: Optional[List[Any]] = Field(
        None,
        description='The Frame of Reference meta data section linking the named properties to self-contained definitions.',
        title='Frame of Reference Meta Data',
    )
    data: Optional[WellData] = None

class WellBoreData(AbstractCommonResources100, AbstractMaster100, AbstractFacility100):
    WellID: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-Well:[\w\-\.\:\%]+:[0-9]*$')
    ] = None
    SequenceNumber: Optional[int] = Field(
        None,
        description='A number that indicates the order in which wellbores were drilled.',
    )
    VerticalMeasurements: Optional[List[VerticalMeasurement]] = Field(
        None,
        description='List of all depths and elevations pertaining to the wellbore, like, plug back measured depth, total measured depth, KB elevation',
    )
    DrillingReasons: Optional[List[AbstractWellboreDrillingReason100]] = Field(
        None, description='The history of drilling reasons of the wellbore.'
    )
    KickOffWellbore: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-Wellbore:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='This is a pointer to the parent wellbore. The wellbore that starts from top has no parent.',
    )
    TrajectoryTypeID: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-WellboreTrajectoryType:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='Describes the predominant shapes the wellbore path can follow if deviated from vertical. Sample Values: Horizontal, Vertical, Directional.',
    )
    DefinitiveTrajectoryID: Optional[
        constr(
            regex=r'^[\w\-\.]+:work-product-component\-\-WellboreTrajectory:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='SRN of Wellbore Trajectory which is considered the authoritative or preferred version.',
    )
    TargetFormation: Optional[
        constr(
            regex=r'^[\w\-\.]+:reference-data\-\-GeologicalFormation:[\w\-\.\:\%]+:[0-9]*$'
        )
    ] = Field(
        None,
        description='The Formation of interest for which the Wellbore is drilled to interact with. The Wellbore may terminate in a lower formation if the requirement is to drill through the entirety of the target formation, therefore this is not necessarily the Formation at TD.',
    )
    PrimaryMaterialID: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-MaterialType:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None, description='The primary material injected/produced from the wellbore.'
    )
    DefaultVerticalMeasurementID: Optional[str] = Field(
        None,
        description='The default datum reference point, or zero depth point, used to determine other points vertically in a wellbore.  References an entry in the Vertical Measurements array of this wellbore.',
    )
    ProjectedBottomHoleLocation: Optional[AbstractSpatialLocation100] = Field(
        None,
        description="The bottom hole location of the wellbore denoted by a projected horizontal coordinate reference system (Horizontal CRS), such a UTM zone. 'Projected' in this property does not mean 'planned' or 'projected-to-bit'. If both GeographicBottomHoleLocation and ProjectedBottomHoleLocation properties are populated on this wellbore, they must identify the same point, just in different CRSs.",
    )
    GeographicBottomHoleLocation: Optional[AbstractSpatialLocation100] = Field(
        None,
        description='The bottom hole location of the wellbore denoted by a specified geographic horizontal coordinate reference system (Horizontal CRS), such as WGS84, NAD27, or ED50. If both GeographicBottomHoleLocation and ProjectedBottomHoleLocation properties are populated on this wellbore, they must identify the same point, just in different CRSs.',
    )
    ExtensionProperties: Optional[Dict[str, Any]] = None


class Wellbore(BaseModel):
    """
    A hole in the ground extending from a point at the earth's surface to the maximum point of penetration.
    """

    id: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-Wellbore:[\w\-\.\:\%]+$')
    ] = Field(
        None,
        description='Previously called ResourceID or SRN which identifies this OSDU resource object without version.',
        example='namespace:master-data--Wellbore:c7c421a7-f496-5aef-8093-298c32bfdea9',
        title='Entity ID',
    )
    kind: constr(regex=r'^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$') = Field(
        ...,
        description='The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.',
        example='osdu:wks:master-data--Wellbore:1.0.0',
        title='Entity Kind',
    )
    version: Optional[int] = Field(
        None,
        description='The version number of this OSDU resource; set by the framework.',
        example=1562066009929332,
        title='Version Number',
    )
    acl: AbstractAccessControlList100 = Field(
        ...,
        description='The access control tags associated with this entity.',
        title='Access Control List',
    )
    legal: AbstractLegalTags100 = Field(
        ...,
        description="The entity's legal tags and compliance status. The actual contents associated with the legal tags is managed by the Compliance Service.",
        title='Legal Tags',
    )
    tags: Optional[Dict[str, Tags]] = Field(
        None,
        description='A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.',
        example={'NameOfKey': 'String value'},
        title='Tag Dictionary',
    )
    createTime: Optional[datetime] = Field(
        None,
        description='Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.',
        example='2020-12-16T11:46:20.163Z',
        title='Resource Object Creation DateTime',
    )
    createUser: Optional[str] = Field(
        None,
        description='The user reference, which created the first version of this resource object. Set by the System.',
        example='some-user@some-company-cloud.com',
        title='Resource Object Creation User Reference',
    )
    modifyTime: Optional[datetime] = Field(
        None,
        description='Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.',
        example='2020-12-16T11:52:24.477Z',
        title='Resource Object Version Creation DateTime',
    )
    modifyUser: Optional[str] = Field(
        None,
        description='The user reference, which created this version of this resource object. Set by the System.',
        example='some-user@some-company-cloud.com',
        title='Resource Object Version Creation User Reference',
    )
    ancestry: Optional[AbstractLegalParentList100] = Field(
        None,
        description='The links to data, which constitute the inputs.',
        title='Ancestry',
    )
    meta: Optional[List[Any]] = Field(
        None,
        description='The Frame of Reference meta data section linking the named properties to self-contained definitions.',
        title='Frame of Reference Meta Data',
    )
    data: Optional[WellBoreData] = None


class WellLogData(
    AbstractCommonResources100, AbstractWPCGroupType100, AbstractWorkProductComponent100
):
    WellboreID: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-Wellbore:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='The Wellbore where the Well Log Work Product Component was recorded',
    )
    WellLogTypeID: Optional[
        constr(regex=r'^[\w\-\.]+:reference-data\-\-LogType:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(
        None,
        description='Well Log Type short Description such as Raw; Evaluated; Composite;....',
    )
    TopMeasuredDepth: Optional[float] = Field(
        None,
        description='OSDU Native Top Measured Depth of the Well Log.',
        title='Top Measured Depth',
    )
    BottomMeasuredDepth: Optional[float] = Field(
        None,
        description='OSDU Native Bottom Measured Depth of the Well Log.',
        title='Bottom Measured Depth',
    )
    ServiceCompanyID: Optional[
        constr(regex=r'^[\w\-\.]+:master-data\-\-Organisation:[\w\-\.\:\%]+:[0-9]*$')
    ] = Field(None, description='Service Company ID')
    LogSource: Optional[str] = Field(
        None,
        description='OSDU Native Log Source - will be updated for later releases - not to be used yet ',
    )
    LogActivity: Optional[str] = Field(
        None,
        description='Log Activity, used to describe the type of pass such as Calibration Pass - Main Pass - Repeated Pass',
    )
    LogRun: Optional[str] = Field(
        None,
        description='Log Run - describe the run of the log - can be a number, but may be also a alphanumeric description such as a version name',
    )
    LogVersion: Optional[str] = Field(None, description='Log Version')
    LoggingService: Optional[str] = Field(
        None,
        description='Logging Service - mainly a short concatenation of the names of the tools',
    )
    LogServiceDateInterval: Optional[LogServiceDateInterval] = Field(
        None,
        description='An interval built from two nested values : StartDate and EndDate. It applies to the whole log services and may apply to composite logs as [start of the first run job] and [end of the last run job]Log Service Date',
    )
    ToolStringDescription: Optional[str] = Field(
        None,
        description='Tool String Description - a long concatenation of the tools used for logging services such as GammaRay+NeutronPorosity',
    )
    LoggingDirection: Optional[str] = Field(
        None, description='Specifies whether curves were collected downward or upward'
    )
    PassNumber: Optional[int] = Field(
        None,
        description="Indicates if the Pass is the Main one (1) or a repeated one - and it's level repetition",
    )
    ActivityType: Optional[str] = Field(
        None,
        description='General method or circumstance of logging - MWD, completion, ...',
    )
    DrillingFluidProperty: Optional[str] = Field(
        None, description='Type of mud at time of logging (oil, water based,...)'
    )
    HoleTypeLogging: Optional[
        constr(regex=r'^OPENHOLE|CASEDHOLE|CEMENTEDHOLE$')
    ] = Field(
        None,
        description='Description of the hole related type of logging - POSSIBLE VALUE : OpenHole / CasedHole / CementedHole',
    )
    VerticalMeasurementID: Optional[str] = Field(
        None,
        description='References an entry in the Vertical Measurement array for the Wellbore identified by WellboreID, which defines the vertical reference datum for all curve measured depths.',
    )
    Curves: Optional[List[Curve]] = None
    ExtensionProperties: Optional[Dict[str, Any]] = None


class WellLog(BaseModel):
    id: Optional[
        constr(regex=r'^[\w\-\.]+:work-product-component\-\-WellLog:[\w\-\.\:\%]+$')
    ] = Field(
        None,
        description='Previously called ResourceID or SRN which identifies this OSDU resource object without version.',
        example='namespace:work-product-component--WellLog:c2c79f1c-90ca-5c92-b8df-04dbe438f414',
        title='Entity ID',
    )
    kind: constr(regex=r'^[\w\-\.]+:[\w\-\.]+:[\w\-\.]+:[0-9]+.[0-9]+.[0-9]+$') = Field(
        ...,
        description='The schema identification for the OSDU resource object following the pattern {Namespace}:{Source}:{Type}:{VersionMajor}.{VersionMinor}.{VersionPatch}. The versioning scheme follows the semantic versioning, https://semver.org/.',
        example='osdu:wks:work-product-component--WellLog:1.0.0',
        title='Entity Kind',
    )
    version: Optional[int] = Field(
        None,
        description='The version number of this OSDU resource; set by the framework.',
        example=1562066009929332,
        title='Version Number',
    )
    acl: AbstractAccessControlList100 = Field(
        ...,
        description='The access control tags associated with this entity.',
        title='Access Control List',
    )
    legal: AbstractLegalTags100 = Field(
        ...,
        description="The entity's legal tags and compliance status. The actual contents associated with the legal tags is managed by the Compliance Service.",
        title='Legal Tags',
    )
    tags: Optional[Dict[str, Tags]] = Field(
        None,
        description='A generic dictionary of string keys mapping to string value. Only strings are permitted as keys and values.',
        example={'NameOfKey': 'String value'},
        title='Tag Dictionary',
    )
    createTime: Optional[datetime] = Field(
        None,
        description='Timestamp of the time at which initial version of this OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.',
        example='2020-12-16T11:46:20.163Z',
        title='Resource Object Creation DateTime',
    )
    createUser: Optional[str] = Field(
        None,
        description='The user reference, which created the first version of this resource object. Set by the System.',
        example='some-user@some-company-cloud.com',
        title='Resource Object Creation User Reference',
    )
    modifyTime: Optional[datetime] = Field(
        None,
        description='Timestamp of the time at which this version of the OSDU resource object was created. Set by the System. The value is a combined date-time string in ISO-8601 given in UTC.',
        example='2020-12-16T11:52:24.477Z',
        title='Resource Object Version Creation DateTime',
    )
    modifyUser: Optional[str] = Field(
        None,
        description='The user reference, which created this version of this resource object. Set by the System.',
        example='some-user@some-company-cloud.com',
        title='Resource Object Version Creation User Reference',
    )
    ancestry: Optional[AbstractLegalParentList100] = Field(
        None,
        description='The links to data, which constitute the inputs.',
        title='Ancestry',
    )
    meta: Optional[List[Any]] = Field(
        None,
        description='The Frame of Reference meta data section linking the named properties to self-contained definitions.',
        title='Frame of Reference Meta Data',
    )
    data: Optional[WellLogData] = None
