# Copyright 2021 Schlumberger
# Copyright 2022 EPAM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

variables:
  PIP_REQUIREMENTS: "requirements.txt requirements_dev.txt"
  IGNORE_PYTHON_SETUP: "wdms_client/request_builders/wdms/recursive_delete/ wdms_client/request_builders/wdms/search_apis/"

  AZURE_SERVICE: wellbore-ddms
  AZURE_DOCKER_SUBDIR: devops/azure/Dockerfile
  AZURE_TEST_SUBDIR: tests/integration
  AZURE_TEST_TYPE: python

  AWS_SERVICE: wellbore-ddms
  AWS_SERVICE_NAMESPACE: osdu-wellbore-ddms
  AWS_ENVIRONMENT: dev
  AWS_BUILD_SUBDIR: provider/os-wellbore-ddms-aws/build-aws
  AWS_TEST_SUBDIR: tests/aws-test/build-aws
  AWS_INT_TEST_TYPE: python
  AWS_DEPLOY_TARGET: EKS
  AWS_EKS_DEPLOYMENT_NAME: os-wellbore-ddms

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/python.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-python.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/osdu-gcp-global.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm-wellbore-git.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-python.yml"

  - local: "/devops/azure/azure-wellbore.yml"
  - local: "devops/gcp/pipeline/override-stages.yml"

#Override Python Image defined in python.yml
.python:
  image: python:3.8-bullseye

verify_existing_requirements:
  tags: ["osdu-small"]
  extends:
    - .python
    - .skipForTriggeringMergeRequests

  stage: build
  before_script:
    - pip3 install --upgrade pip-tools

  script:
    - pip-compile requirements.in
    - pip-compile requirements_dev.in
    - git diff
    # checking difference between existing requirements and the newly generated one
    # and using the number of lines as exit status code
    - exit $(git status -s | grep -e "^ M " | wc -l)

  artifacts:
    when: always
    paths:
      - "requirements*.txt"

    expire_in: 2 days

compile-and-unit-test:
  artifacts:
    when: always
    paths:
      - all-requirements.txt
      - ./**/python-*-output.txt
      - spec/generated/openapi.json

verify_models:
  tags: ["osdu-small"]
  extends:
    - .python
    - .skipForTriggeringMergeRequests

  stage: build

  script:
    - python -m doctest docs/model/model_curated.md

containerize:
  extends: .skipForTriggeringMergeRequests
  stage: containerize
  image: docker:19.03
  tags: ["osdu-small"]
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  script:
    - echo ---- ---- ---- SYSTEM DEPENDENCIES ---- ---- ----
    - apk update
    - apk add git
    - echo ---- ---- ---- BUILD IMAGE ---- ---- ----
    - commit_id=$(git log -n 1 --pretty="%h")
    - echo ---- ---- TAG NAME
    - tag_name="_gitlab_$commit_id"
    - echo $tag_name
    - echo ---- ---- DATE
    - current_utc_date=`date --utc`
    - echo $current_utc_date
    - echo ---- ---- COMMIT BRANCH
    - commit_branch=$commit_id
    - echo $commit_branch
    - echo ---- ---- BUILD IMAGE
    - docker build -t $IMAGE_TAG -t=$CI_REGISTRY_IMAGE:latest --rm . -f ./build/Dockerfile --build-arg PIP_WHEEL_DIR=python-packages --build-arg build_date="$current_utc_date" --build-arg build_number=$commit_id --build-arg commit_id=$commit_id --build-arg build_origin="Gitlab" --build-arg commit_branch=$commit_branch
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo ---- ---- PUSH IMAGE
    - docker push $IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:latest

# Allow failure on flaky deployments
aws-update-eks:
  allow_failure: true
ibm-deploy:
  allow_failure: true
ibm-test:
  allow_failure: true

# Allow failure on private development deployments
ibm-deploy-devpri:
  allow_failure: true
aws-test-python:
  allow_failure: true
