stages:
  - pytest
  - build
  - test

build:
  stage: pytest
  image: python:3.7-slim-buster
  script:
    - echo ---- ---- ---- SYSTEM DEPENDENCIES ---- ---- ----
    - apt update
    - apt install -y --no-install-recommends git
    - echo ---- ---- ---- BUILD IMAGE ---- ---- ----
    - pip3 install -r requirements.txt
    - pip3 install -r requirements_opengroup.txt
    - pip3 install -r requirements_dev.txt
    - echo ---- ---- ---- UNIT TESTS ---- ---- ----
    - pytest --junit-xml=unit_tests_report.xml --cov=app --cov-report=xml:coverage.xml --cov-report=term ./tests/unit
  coverage: '/^(?i)(TOTAL).*\s+(\d+\%)$/'
  artifacts:
    when: always
    reports:
      junit: unit_tests_report.xml
      cobertura: coverage.xml

deploy:
  stage: build
  image: docker:18.09.7-dind
  variables:
      IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:18.09.7-dind
      entrypoint: ["env", "-u", "DOCKER_TLS_CERTDIR"]
      command: ["dockerd-entrypoint.sh"]

  script:
    - echo ---- ---- ---- SYSTEM DEPENDENCIES ---- ---- ----
    - apk update
    - apk add git
    - echo ---- ---- ---- BUILD IMAGE ---- ---- ----
    - commit_id=$(git log -n 1 --pretty="%h")
    - echo ---- ---- TAG NAME
    - tag_name="_gitlab_$commit_id"
    - echo $tag_name
    - echo ---- ---- DATE
    - current_utc_date=`date --utc`
    - echo $current_utc_date
    - echo ---- ---- COMMIT BRANCH
    - commit_branch=$commit_id
    - echo $commit_branch
    - echo ---- ---- BUILD IMAGE
    - docker build -t $IMAGE_TAG -t=$CI_REGISTRY_IMAGE:latest --rm . -f ./build/Dockerfile --build-arg PIP_WHEEL_DIR=python-packages --build-arg build_date="$current_utc_date" --build-arg build_number=$commit_id --build-arg commit_id=$commit_id --build-arg build_origin="Gitlab" --build-arg commit_branch=$commit_branch
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo ---- ---- PUSH IMAGE
    - docker push $IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
#Scanning for vulnerabilities
include:
  - template: Container-Scanning.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml