data:
  logLevel: "ERROR"
  requestsCpu: "130m"
  requestsMemory: "750Mi"
  limitsCpu: "1"
  limitsMemory: "3G"
  image: ""
  imagePullPolicy: "IfNotPresent"
  serviceAccountName: "wellbore"
  projectId: ""
conf:
  configmap: "wellbore-config"
  appName: "wellbore"
  keycloakSecretName: "wellbore-keycloak-secret"
  minioSecretName: "wellbore-minio-secret"
  domain: ""
  onPremEnabled: false

istio:
  proxyCPU: "10m"
  proxyCPULimit: "500m"
  proxyMemory: "100Mi"
  proxyMemoryLimit: "512Mi"
