data:
  requestsCpu: "0.1"
  requestsMemory: "1G"
  limitsCpu: "1"
  limitsMemory: "3G"
  image: ""
  imagePullPolicy: "IfNotPresent"
  serviceAccountName: "wellbore"
  projectId: ""
conf:
  configmap: "wellbore-config"
  appName: "wellbore"
  keycloakSecretName: "wellbore-keycloak-secret"
  minioSecretName: "wellbore-minio-secret"
  domain: ""
  onPremEnabled: false

istio:
  proxyCPU: "50m"
  proxyCPULimit: "500m"
  proxyMemory: "64Mi"
  proxyMemoryLimit: "512Mi"
