{{- template "common.serviceparameters" (list . "os-wellbore-ddms.serviceparameters") -}}
{{- define "os-wellbore-ddms.serviceparameters" -}}
## Define overrides for the service parameters here
{{- end -}}