apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.conf.appName | quote }}
  name: {{ .Values.conf.configmap | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
  LOG_LEVEL: {{ .Values.data.logLevel | quote }}
  {{- if .Values.global.wdms_workers.enabled }}
  SERVICE_HOST_WDMS_WORKER: {{ printf "%s/api/wdms-worker" .Values.data.WDMSWorkerHost | quote }}
  {{- end }}
  KEYCLOAK_AUTH: "yes"
  BASE_BUCKET: "wellbore"
  CLOUD_PROVIDER: "baremetal"
  DE_CLIENT_CFG_TIMEOUT: "30"
