variables:
  CORE_SERVICE: wellbore
  CORE_INT_TEST_TYPE: python
  CORE_BAREMETAL_PYTHON_INT_TEST_SUBDIR: tests/baremetal

core-containerize-gitlab:
  needs:
    - "compile-and-unit-test"
  variables:
    CORE_BUILD_PATH: "./build/Dockerfile"
    CORE_BUILD_ARGS: >
      --build-arg PIP_WHEEL_DIR=python-packages
      --build-arg build_date="$CI_JOB_STARTED_AT"
      --build-arg build_number=$CI_COMMIT_SHORT_SHA
      --build-arg commit_id=$CI_COMMIT_SHORT_SHA
      --build-arg build_origin="Gitlab"
      --build-arg commit_branch=$CI_COMMIT_BRANCH

core-test-python:
  variables:
    GC_WELLBORE_BASE_URL: https://osdu.core-dev.gcp.gnrg-osdu.projects.epam.com/api/os-wellbore-ddms
