apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  annotations:
{{ include "os-wellbore-ddms.commonAnnotations" . | indent 4}}
  labels:
{{ include "os-wellbore-ddms.commonLabels" . | indent 4}}
  name: {{ .Values.authorizationPolicy.name }}{{ include "os-wellbore-ddms.name-suffix" . }}
{{ include "os-wellbore-ddms.namespace" . | indent 2}}
spec:
  action: DENY
  rules:
  - from:
    - source:
        notRequestPrincipals:
        - '*'
    to:
    - operation:
        notPaths:
        - {{ include "os-wellbore-ddms.prefix" . }}/
        - {{ include "os-wellbore-ddms.prefix" . }}/ddms/v2/about
        - {{ include "os-wellbore-ddms.prefix" . }}/docs
        - {{ include "os-wellbore-ddms.prefix" . }}/openapi.json
  selector:
    matchLabels:
{{ include "os-wellbore-ddms.commonLabels" . | indent 6}}
