# Default values for gcp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: wellbore

configMap:
  data:
    cloudProvider: gcp
    projectId: nice-etching-277309
    searchEndpoint: https://os-search-attcrcktoa-uc.a.run.app/api/search
    entitlementsEndpoint: https://os-entitlements-gcp-attcrcktoa-uc.a.run.app/entitlements/v1/
    storageEndpoint: https://os-storage-attcrcktoa-uc.a.run.app/api/storage
  name: wellbore

secret:
  name: wellbore
  key: "key.json"
  gcpSA: "" #ENTER in base64 service-account value

replicaCount: 1

image:
  repository: "gcr.io/nice-etching-277309/wellbore-ddms/wellbore-ddms-gcp"
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "7e6b01b5"

service:
  #type: ClusterIP
  type: NodePort
  port: 8080

ingress:
  enabled: true
  annotations:
     kubernetes.io/ingress.class: gcp
    # kubernetes.io/tls-acme: "true"
#  hosts:
#    - host: chart-example.local
#      paths: []
#  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#  limits:
#    cpu: 800m
#    memory: 512Mi
#  requests:
#    cpu: 700m
#    memory: 512Mi
