kind: ConfigMap
apiVersion: v1
data:
  # System sevice variables
  CLOUD_PROVIDER: gcp
  OS_WELLBORE_DDMS_DATA_PROJECT_ID: nice-etching-277309
  SERVICE_HOST_SEARCH: https://os-search-attcrcktoa-uc.a.run.app/api/search
  SERVICE_HOST_STORAGE: https://os-storage-attcrcktoa-uc.a.run.app/api/storage
  # Custom variables
  IMAGE_NAME: community.opengroup.org:5555/osdu/platform/domain-data-mgmt-services/wellbore/wellbore-domain-services/gcp-trusted-gonrg-2066-release-wellbore-pipe-k8s
  IMAGE_TAG: gcp-community
  HEALTH_URL: /api/os-wellbore-ddms/healthz
  API_URL: /api/os-wellbore-ddms
  SERVICE_NAME: wellbore
  TENANT: osdu
  LEGAL_TAG: osdu-demo-legaltag
  DEPLOYMENT_DIR: devops/gcp/osdu-helm

metadata:
  name: wellbore
  namespace: wellbore
---
kind: Secret
apiVersion: v1
metadata:
  name: wellbore
  namespace: wellbore
type: Opaque
data:
  "key.json": ""