# Default values for wellbore-configmap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

data:
  os_wellbore_ddms_data_project_id: ""
  service_host_search: "http://search/api/search"
  service_host_storage: "http://storage/api/storage"
  

conf:
  configmap: "wellbore-config"
  app_name: "wellbore"
