apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "gcp.fullname" . }}
  labels:
    {{- include "gcp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gcp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gcp.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: service-account-key
          secret:
            secretName:  {{ .Values.secret.name }}
      containers:
        - name: {{ .Chart.Name }}
          volumeMounts:
            - mountPath: /tmp/key
              name: service-account-key
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}
          env:
            - name: OS_WELLBORE_DDMS_DATA_PROJECT_CREDENTIALS
              value: /tmp/key/{{ .Values.secret.key }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/os-wellbore-ddms/healthz
              port: http
          readinessProbe:
            httpGet:
              path: /api/os-wellbore-ddms/healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
