#kind: Secret
#apiVersion: v1
#metadata:
#  name: {{ .Values.secret.name }}
#  namespace: {{ .Values.namespace }}
#type: Opaque
#data:
#  {{ .Values.secret.key | quote }}: {{ .Values.secret.gcpSA | quote }}
