apiVersion: v1
kind: Service
metadata:
  name: {{ include "gcp.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "gcp.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "gcp.selectorLabels" . | nindent 4 }}
