# Copyright 2021 Schlumberger
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for os-wellbore-ddms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: osdu
deployment:
  instrumentationKey:
    secretName: central-logging
  osduSvcProperties: osdu-svc-properties
  keyvaultUrlPropertyName: ENV_KEYVAULT
  name: os-wellbore-ddms

nodepool: services
isAutoscalingEnabled: false
maxReplicaCount: 2
minReplicaCount: 2
replicaCount: 2

resources:
 limits:
   memory: 2Gi
 requests:
   memory: 2Gi

probes:
  startup:
    failureThreshold: 6
    periodSeconds: 5
  liveness:
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 6
  readiness:
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 1
    successThreshold: 5

annotations:
  buildNumber: []
  buildOrigin: AzureDevops build/#{Build.DefinitionName}#
  commitBranch: []
  commitId: []

image:
  repository: community.opengroup.org:5555/osdu/platform/domain-data-mgmt-services/wellbore/wellbore-domain-services/wellbore-domain-services-master
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest


tempDeployment:
  enabled: false
  name: prxxxx

labels:
  aadpodidbinding: osdu-identity
  env: gitlab

configMap:
  data:
    storageEndpoint: http://storage.osdu/api/storage
    searchEndpoint: http://search-service.osdu/api/search
    partitionEndpoint: http://partition.osdu/api/partition
    usePartitionService: 'enabled'
    loggerLevel: 'INFO'
    environmentName: gitlab
    modules: log_recognition.routers.log_recognition
  name: os-wellbore-ddms-envs

ingress:
  enabled: false
  extraAnnotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/request-timeout: "300"
    appgw.ingress.kubernetes.io/connection-draining: "true"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
    kubernetes.io/ingress.class: azure/application-gateway
  hosts:
    host: # leave it empty for our dev cluster
    pathPrefix: /api/os-wellbore-ddms
  tlsSecret: osdu-certificate

authorizationPolicy:
  name: wellbore-jwt-authz


istioDnsHost: ""