apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Values.conf.app_name }}"
  labels:
    app: "{{ .Values.conf.app_name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.conf.app_name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.conf.app_name }}"
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: "{{ .Values.data.serviceAccountName }}"
      containers:
        - name: "{{ .Values.conf.app_name }}"
          image: "{{ .Values.data.image }}"
          imagePullPolicy: "{{ .Values.data.imagePullPolicy }}"
          envFrom:
            - configMapRef:
                name: "{{ .Values.conf.configmap }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/os-wellbore-ddms/healthz
              port: http
          readinessProbe:
            httpGet:
              path: /api/os-wellbore-ddms/healthz
              port: http
          resources:
            requests:
              cpu: "{{ .Values.data.requests_cpu }}"
              memory: "{{ .Values.data.requests_memory }}"
            limits:
              cpu: "{{ .Values.data.limits_cpu }}"
              memory: "{{ .Values.data.limits_memory }}"
