apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ .Values.conf.app_name }}"
  name: "{{ .Values.conf.configmap }}"
  namespace: "{{ .Release.Namespace }}"
data:
  CLOUD_PROVIDER: "gcp"
  OS_WELLBORE_DDMS_DATA_PROJECT_ID: "{{ .Values.data.os_wellbore_ddms_data_project_id }}"

