apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ .Values.conf.appName }}"
  name: "{{ .Values.conf.configmap }}"
  namespace: "{{ .Release.Namespace }}"
data:
  {{- if not .Values.conf.onPremEnabled }}
  CLOUD_PROVIDER: "gcp"
  OS_WELLBORE_DDMS_DATA_PROJECT_ID: "{{ .Values.data.projectId }}"
  {{- else }}
  KEYCLOAK_AUTH: "yes"
  BASE_BUCKET: "wellbore"
  CLOUD_PROVIDER: "anthos"
  {{- end }}
