variables:
  GC_SERVICE: wellbore
  GC_VENDOR: gc
  GC_INT_TEST_TYPE: python
  GC_BAREMETAL_PYTHON_INT_TEST_SUBDIR: tests/baremetal
  GC_PYTHON_INT_TEST_SUBDIR: tests/gc

gc-containerize-gitlab:
  variables:
    BUILD_PATH: "./build/Dockerfile"
    BUILD_ARGS: >
      --build-arg PIP_WHEEL_DIR=python-packages
      --build-arg build_date="$CI_JOB_STARTED_AT"
      --build-arg build_number=$CI_COMMIT_SHORT_SHA
      --build-arg commit_id=$CI_COMMIT_SHORT_SHA
      --build-arg build_origin="Gitlab"
      --build-arg commit_branch=$CI_COMMIT_BRANCH

gc-containerize-gcr:
  variables:
    BUILD_PATH: "./build/Dockerfile"
    BUILD_ARGS: >
      --build-arg PIP_WHEEL_DIR=python-packages
      --build-arg build_date="$CI_JOB_STARTED_AT"
      --build-arg build_number=$CI_COMMIT_SHORT_SHA
      --build-arg commit_id=$CI_COMMIT_SHORT_SHA
      --build-arg build_origin="Gitlab"
      --build-arg commit_branch=$CI_COMMIT_BRANCH

gc-baremetal-test-python:
  image: python:3.8
  allow_failure: true

# Disable maven job in gc-com-gke pipelines
gc-test:
  extends:
    - .gc-variables

gc-dev2-test:
  extends:
    - .gc-dev2-variables

gc-baremetal-test:
  extends:
    - .gc-baremetal-variables
