# Copyright 2021 Schlumberger
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

parameters:
  - name: baseUrl
    type: string
  - name: osduBaseUrl
    type: string
    default: "" # if empty will use baseUrl instead
  - name: basePath
    type: string
  - name: cloudProvider
    type: string
  - name: aclDomain
    type: string
  - name: legalTag
    type: string
  - name: dataPartition
    type: string
  - name: environmentName
    type: string
    default: "UndefinedEnv"
  - name: schemasVersionsListJson
    type: string
  - name: skipCertValidation
    # Used in case of invalid certificate (self-signed,...) 
    type: boolean
    default: false
# The following parameters allow to inject a template intented to perform authentication and generate a token
# the token is to be added as a secure output variable:
#   echo "##vso[task.setvariable variable=token;issecret=true]${token}"
  - name: authenticationTemplate
    type: string
    default: ""
  - name: authenticationTemplateParameters
    type: object
    default: {}

steps:

- bash: |
      set -e

      echo "parameters.skipCertValidation: ${{ parameters.skipCertValidation }}"
      echo "parameters.baseUrl: ${{ parameters.baseUrl }}"
      echo "parameters.osduBaseUrl: ${{ parameters.osduBaseUrl }}"
      echo "parameters.basePath: ${{ parameters.basePath }}"
      echo "parameters.cloudProvider: ${{ parameters.cloudProvider }}"
      echo "parameters.aclDomain: ${{ parameters.aclDomain }}"
      echo "parameters.legalTag: ${{ parameters.legalTag }}"
      echo "parameters.dataPartition: ${{ parameters.dataPartition }}"
      echo "parameters.environmentName: ${{ parameters.environmentName }}"
      echo "parameters.schemasVersionsListJson: ${{ parameters.schemasVersionsListJson }}"
  displayName: 'Display Info'

- task: Bash@3
  displayName: 'testReportBaseName'
  inputs:
    targetType: 'inline'
    script: |
        prefix=$(System.StageName)#$(System.JobAttempt)
        echo "##vso[task.setvariable variable=testReportBaseName]${prefix}"

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    addToPath: true


# This template is injected by parameters
# and will generate the $(token) variable
- template: ${{ parameters.authenticationTemplate }}
  parameters: 
    ${{ each parameter in parameters.authenticationTemplateParameters }}:
      ${{ parameter.key}}: ${{ parameter.value}}


- bash: |
    set -e

    insecure_flag=""
    test_alpha_feature_flag=""
    checkCert="True"

    # Depending on the value of 'skipCertValidation' we add the '--insecure' option to newman
    # and update checkCert for pytest
    skipCertValidation="${{ lower(parameters.skipCertValidation) }}"
    if $skipCertValidation
    then
      echo "Adding --insecure flag to e2e tests to disable cert validation."
      insecure_flag="--insecure"
      checkCert=""

      # in that case it means dev env, in that case enable test on alpha feature
      echo "skipCertValidation case: adding --test-alpha-feature flag to e2e tests to enable test on alpha features."
      test_alpha_feature_flag="--test-alpha-feature"
    fi

    # Depending on the value of environmentName, activate test on alpha feature
    envName="${{ parameters.environmentName }}"
    if [ "$envName" = "evd" ] || [ "$envName" = "dev" ] || [ "$envName" = "qa" ];
    then
      echo "Env = $envName: adding --test-alpha-feature flag to e2e tests to enable test on alpha features."
      test_alpha_feature_flag="--test-alpha-feature"
    fi

    echo "##vso[task.setvariable variable=insecure_flag]${insecure_flag}"
    echo "##vso[task.setvariable variable=test_alpha_feature_flag]${test_alpha_feature_flag}"
    echo "##vso[task.setvariable variable=checkCert]${checkCert}"

  displayName: 'Create test variables'

- bash: |
    set -e

    osduBaseUrl=${{ parameters.osduBaseUrl }}
    if [ -z "$osduBaseUrl" ]
    then
          osduBaseUrl=${{ parameters.baseUrl }}
    fi

    python tests/integration/gen_postman_env.py --token $(token) --base_url ${osduBaseUrl} --cloud_provider ${{ parameters.cloudProvider }} --acl_domain ${{ parameters.aclDomain }} --legal_tag ${{ parameters.legalTag }} --data_partition ${{ parameters.dataPartition }}

    newman run tests/dependencies/core_dependencies_test.postman_collection.json -e generated/postman_environment.json -r junit,cli --reporter-junit-export dependencies_tests_report_$(testReportBaseName).xml --timeout-request 10000 $(insecure_flag)

  displayName: 'Check healthiness of Core services'
  condition: ne('${{ parameters.cloudProvider }}', 'gcp')
  continueOnError: true

- bash: |
    set -e

    appUrl=${{ parameters.baseUrl }}${{ parameters.basePath }}
    echo "Testing App on ${appUrl}"

    python tests/integration/gen_postman_env.py --token $(token) --base_url ${appUrl} --cloud_provider ${{ parameters.cloudProvider }} --acl_domain ${{ parameters.aclDomain }} --legal_tag ${{ parameters.legalTag }} --data_partition ${{ parameters.dataPartition }}

    pip install virtualenv
    virtualenv venv37
    source venv37/bin/activate
    pip install -r ./requirements_dev.txt

    pytest tests/integration/functional/ --filter-tag=!search --junit-xml=$(testReportBaseName)_int_tests_report.xml \
        -o junit_suite_name="wdms_integration_$(testReportBaseName)" --environment=generated/postman_environment.json \
        --retry-on-error=502 \
        $(insecure_flag) \
        $(test_alpha_feature_flag) \
        --param=ENVIRONMENT_NAME:$ENVIRONMENT_NAME
    deactivate
  displayName: 'RUN INTEGRATION-E2E'
  env:
    ENVIRONMENT_NAME: ${{ parameters.environmentName }}

- bash: |
    set -e

    pip install virtualenv
    virtualenv venv37
    source venv37/bin/activate
    pip install -r ./requirements_dev.txt

    appUrl=${{ parameters.baseUrl }}${{ parameters.basePath }}
    echo "Testing App on ${appUrl}"

    pytest tests/integration/security/test_auth.py --base_url ${appUrl} --check_cert "$(checkCert)" --token="$(token)" --junit-xml=$(testReportBaseName)_auth_tests_report.xml -o junit_suite_name="wdms_auth_$(testReportBaseName)"

    deactivate
  displayName: 'RUN INTEGRATION-AUTH'


- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*tests_report*.xml'
  condition: always()
