parameters:
  - name: testSA
    type: string
    default: "" #Needed only for Google Test SA
  - name: deAudience
    type: string
    default: "" #Needed only for Google Test SA
  - name: baseUrl
    type: string
  - name: osduBaseUrl
    type: string
    default: "" # if empty will use baseUrl instead
  - name: basePath
    type: string
  - name: cloudProvider
    type: string
  - name: aclDomain
    type: string
  - name: legalTag
    type: string
  - name: dataPartition
    type: string
  - name: testServiceAccount
    type: object
  - name: skipCertValidation
    # Used in case of invalid certificate (self-signed,...) 
    type: boolean
    default: false

steps:

- bash: |
      set -e

      echo "parameters.skipCertValidation: ${{ parameters.skipCertValidation }}"
      echo "parameters.baseUrl: ${{ parameters.baseUrl }}"
      echo "parameters.osduBaseUrl: ${{ parameters.osduBaseUrl }}"
      echo "parameters.basePath: ${{ parameters.basePath }}"
      echo "parameters.cloudProvider: ${{ parameters.cloudProvider }}"
      echo "parameters.aclDomain: ${{ parameters.aclDomain }}"
      echo "parameters.legalTag: ${{ parameters.legalTag }}"
      echo "parameters.dataPartition: ${{ parameters.dataPartition }}"
      echo "parameters.testServiceAccount.type: ${{ parameters.testServiceAccount.type }}"
  displayName: 'Display Info'

- task: Bash@3
  displayName: 'testReportBaseName'
  inputs:
    targetType: 'inline'
    script: |
        prefix=$(System.StageName)#$(System.JobAttempt)
        echo "##vso[task.setvariable variable=testReportBaseName]${prefix}"

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    addToPath: true



#############
# TO_BE_DEFINED
#------------
# In the current version, here should be a couple of tasks which goal is to generate a token to be used for integration tests.
# the 'testServiceAccount' parameter could be used to pass information on how to get the token (reference to secret, type of Identity Provider...)
#
# the token is to be added as a secure output variable:
#   echo "##vso[task.setvariable variable=token;issecret=true]${token}"
#
# The following section for a GCP Service Account Token is given as example.
# A better approach could eventually be considered such as:
# - pass the token as parameter, and delegate to a higher task the responsibility to generate the token depending on the Service Account Type
# - use some kind of injection mechanism to include a template specific to the service account type
# 
###########

### GCP Service Account based token
- ${{ if eq(parameters.testServiceAccount.type, 'gcp') }}:
  - task: DownloadSecureFile@1
    displayName: 'Download secret File : ${{parameters.testServiceAccount.secretFile}}'
    name: secretFile
    inputs:
      secureFile: ${{ parameters.testServiceAccount.secretFile }}

  - bash: |
        set -e
        gcloud auth activate-service-account --key-file $(secretFile.secureFilePath)
    displayName: 'SETUP - Authenticate for GCP'
    
  - task: Bash@3
    displayName: 'Generate Token for GCP'
    inputs:
      targetType: 'inline'
      script: |
        token=$(gcloud auth print-identity-token --audiences=${{ parameters.deAudience }})
        echo "##vso[task.setvariable variable=token;issecret=true]${token}"
### End of GCP Service Account based token


- bash: |
    set -e

    insecure_flag=""
    checkCert="True"

    # Depending on the value of 'skipCertValidation' we add the '--insecure' option to newman
    # and update checkCert for pytest
    skipCertValidation="${{ lower(parameters.skipCertValidation) }}"
    if $skipCertValidation
    then
      echo "Adding --insecure flag to newman to disable cert validation."
      insecure_flag="--insecure"
      checkCert=""
    fi

    echo "##vso[task.setvariable variable=insecure_flag]${insecure_flag}"
    echo "##vso[task.setvariable variable=checkCert]${checkCert}"

  displayName: 'Create test variables'

- bash: |
    set -e

    osduBaseUrl=${{ parameters.osduBaseUrl }}
    if [ -z "$osduBaseUrl" ]
    then
          osduBaseUrl=${{ parameters.baseUrl }}
    fi

    python tests/integration/gen_postman_env.py --token $(token) --base_url ${osduBaseUrl} --cloud_provider ${{ parameters.cloudProvider }} --acl_domain ${{ parameters.aclDomain }} --legal_tag ${{ parameters.legalTag }} --data_partition ${{ parameters.dataPartition }}

    newman run tests/dependencies/core_dependencies_test.postman_collection.json -e generated/postman_environment.json -r junit,cli --reporter-junit-export dependencies_tests_report_$(testReportBaseName).xml --timeout-request 10000 $(insecure_flag)

  displayName: 'Check healthiness of Core services'
  condition: ne('${{ parameters.cloudProvider }}', 'gcp')
  continueOnError: true

- bash: |
    set -e

    appUrl=${{ parameters.baseUrl }}${{ parameters.basePath }}
    echo "Testing App on ${appUrl}"
    
    python tests/integration/gen_postman_env.py --token $(token) --base_url ${appUrl} --cloud_provider ${{ parameters.cloudProvider }} --acl_domain ${{ parameters.aclDomain }} --legal_tag ${{ parameters.legalTag }} --data_partition ${{ parameters.dataPartition }}

    pip install virtualenv
    virtualenv venv37
    source venv37/bin/activate
    pip install -r ./requirements_dev.txt

    pytest tests/integration/functional/ --junit-xml=$(testReportBaseName)_int_tests_report.xml -o junit_suite_name="wdms_integration_$(testReportBaseName)" --environment=generated/postman_environment.json $(insecure_flag) --retry-on-error=502
    deactivate
  displayName: 'RUN INTEGRATION-E2E'

- bash: |
    set -e

    pip install virtualenv
    virtualenv venv37
    source venv37/bin/activate
    pip install -r ./requirements_dev.txt

    appUrl=${{ parameters.baseUrl }}${{ parameters.basePath }}
    echo "Testing App on ${appUrl}"

    pytest tests/integration/security/test_auth.py --base_url ${appUrl} --check_cert "$(checkCert)" --token="$(token)" --junit-xml=$(testReportBaseName)_auth_tests_report.xml -o junit_suite_name="wdms_auth_$(testReportBaseName)"

    deactivate
  displayName: 'RUN INTEGRATION-AUTH'


- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*tests_report*.xml'
  condition: always()
