kind: ConfigMap
apiVersion: v1
data:
  CLOUD_PROVIDER: gcp
  OS_WELLBORE_DDMS_DATA_PROJECT_ID: {{ .Values.configMap.data.projectId }}
  SERVICE_HOST_STORAGE: {{ .Values.configMap.data.storageEndpoint }}
  SERVICE_HOST_SEARCH: {{ .Values.configMap.data.searchEndpoint }}
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}

