apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "gcp.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: {{ include "gcp.fullname" . }}
              servicePort: 8080

