kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{ .Values.secret.name | quote }}: {{ .Values.secret.gcpSA | b64enc | quote }}